import books


def books_manager():
    connention = books.connect()
    books.create_table(connention)
    # TODO: Dodawanie książek
    books.add_book(connention, 1, "Zemsta", "Aleksander Fredro", "9788304016934", "Spór o mur.")
    books.add_book(connention, 2, "Start a fire. Runda pierwsza", "P.S. Herytiera", "", """"Wznieciliśmy ogień, nad którym nie byliśmy w stanie zapanować

Victoria Joseline Clark nigdy nie należała do szczególnie rozważnych dziewczyn, choć nie można jej było zarzucić braku inteligencji. Przez siedemnaście lat swojego życia uważała się za osobę przeciętną i taką również prowadziła egzystencję. Nauka w renomowanym liceum, wieczne kłótnie z irytującym bratem bliźniakiem, częste imprezy z przyjaciółmi, rodzinne kolacje w towarzystwie troskliwej matki i wiernego psa ― niczym się nie wyróżniała z tłumu innych dzieciaków z małego miasteczka Culver City w stanie Kalifornia, słynącego z turystów, kina i dobrego jedzenia. Jej rodzice mieli jeden cel: wychować swoje dzieci na porządnych obywateli. Victorii od małego wpajano żelazne zasady, których ślepo przestrzegała, przekonana, że uchronią ją przed problemami, o których opowiadała jej matka. Niestety, dziewczyny nie przygotowano na to, że jej największym utrapieniem może się okazać wysoki chłopak z martwym spojrzeniem i zimnym uśmiechem. Wystarczyło kilka źle dobranych słów i obecność w niewłaściwym miejscu o nieodpowiedniej porze, aby zapoczątkować walkę, na którą nie była gotowa. Wszystko wymknęło się spod kontroli, gdy ten czarnooki, zblazowany chłopak okazał się faworytem nielegalnych pojedynków bokserskich, których od lat nienawidzi jej matka ― prawa ręka burmistrza miasta i oddana przyjaciółka funkcjonariuszy policji.

Victoria najchętniej cofnęłaby czas. Ilekroć spoglądała w czarne jak noc oczy, błagała w myślach, aby nigdy ich nie zobaczyć. On był problemem, którego nie potrafiła rozwiązać. Chaosem, który nadszedł. Mrokiem, do którego lgnęła. Ósmym grzechem głównym, który chciała popełnić. Błagała o rozgrzeszenie, które nie nadchodziło. Bo oboje byli zbyt wielkimi grzesznikami.

Czy zdobędziesz się na odwagę, aby otworzyć oczy? Czy pozostawisz je zamknięte już na zawsze?
""")
    books.add_book(connention, 3, "Diuna", "Frank Herbert", "978-83-8188-057-2", """"Arrakis, zwana Diuną, to jedyne we wszechświecie źródło melanżu. Z rozkazu Padyszacha Imperatora planetę przejmują Atrydzi, zaciekli wrogowie władających nią dotychczas Harkonnenów. Zwycięstwo księcia Leto Atrydy jest jednak pozorne – przejęcie planety ukartowano. W odpowiedzi na atak Imperium i Harkonnenów dziedzic rodu Atrydów Paul staje na czele rdzennych mieszkańców Diuny i sięga po imperialny tron. Oszałamiające połączenie przygody oraz mistycyzmu, ekologii i polityki.
"Diuna" otrzymała dwie najbardziej prestiżowe nagrody SF: Nebula i Hugo.
Dom Wydawniczy REBIS oddaje czytelnikom nowe, poprawione wydanie cyklu „Kroniki Diuny”, który tworzą: "Diuna", "Mesjasz Diuny", "Dzieci Diuny", "Bóg Imperator Diuny", "Heretycy Diuny" i "Kapitularz Diuną".
Najnowszą ekranizację "Diuny" wyreżyserował Denis Villeneuve ("Blade Runner 2049", "Sicario"). Autorami scenariusza są Eric Roth ("Forrest Gump"), Jon Spaihts ("Doktor Strange") i Denis Villeneuve, a muzyki – Hans Zimmer ("Gladiator", "Incepcja", "Dunkierka"). W obsadzie gwiazdy światowego kina: Timothée Chalamet, Rebecca Ferguson, Stellan Skarsgård, Jason Momoa, Charlotte Rampling, Javier Bardem, Josh Brolin, Zendaya i Oscar Isaac.""")
    books.add_book(connention, 4, "Zaraza", "Przemysław Piotrowski", "", """"Po tym, jak cudem uszedł z życiem z zasadzki psychopatycznego mordercy, Igor Brudny powoli i z trudem dochodzi do siebie. Świat, w którym się obudził, nie jest już jednak taki sam. Komisarz musi trzymać się z dala od Warszawy, a zielonogórski zespół inspektora Romualda Czarneckiego już nie istnieje. Ale przynajmniej dawna partnerka Brudnego, Julia Zawadzka, wciąż jest przy nim.
 
Sama Zawadzka, po przeniesieniu do komendy w Zielonej Górze, również mierzy się z nowymi wyzwaniami. Prowadzone przez nią śledztwo utknęło w martwym punkcie, a w dodatku w pobliskim lesie znaleziono zwłoki kolejnej zamordowanej kobiety. Wyniki sekcji są jasne: w ciele ofiary nie została prawie żadna kropla krwi. Do tego jeszcze dochodzi ofiara wypadku samochodowego, o której Zawadzka wolałaby zapomnieć…
 
Wszystko wskazuje na to, że nad Zieloną Górą zbierają się ciemne chmury. Sfrustrowany własną bezradnością Brudny zastanawia się, czy zło, które znał tak dobrze, znów pojawiło się w mieście. Któregoś dnia w jego domu niespodziewanie pojawia się ktoś, kto desperacko potrzebuje pomocy. Czy pokiereszowany komisarz znajdzie w sobie siłę, by rozwiązać jeszcze jedną sprawę?
""")
    books.add_book(connention, 5, "Kmioty polskie", "Robert Mazurek, Krzysztof Stanowski", "",
                   "Tomik autorstwa Krzysztofa Stanowskiego i Roberta Mazurka, stojących na czele nowej fali polskiej poezji, zwanej poezją błyskawiczną - a to dlatego, że napisanie jednego dzieła z założenia ma zajmować nie więcej niż sześć minut i 18 sekund. Cały dochód zostanie właściwie rozdysponowany")
    books.add_book(connention, 6, "Też tak mam", "Magdalena Kostyszyn", "978-83-280-9488-8", """„A w tej czapeczce nie będzie córce za ciepło?” „Depresja? Jaka depresja? Poszłabyś do normalnej pracy, to by ci przeszło.”, „Za bardzo boli? To okres, musi boleć.”
Tak, o naszym życiu można powiedzieć jeszcze wiele rzeczy. Można strywializować kolejne jego aspekty, ośmieszyć problemy, unieważnić to, co czujemy.
Można zapytać czy kobieta pracująca na tym samym stanowisku co mężczyzna, powinna zarabiać mniej od niego? Można zapytać o to, czy zajmowanie się domem to hobby, czy może jednak praca? O to, czy komentarz „fajne masz cycki” jest komplementem. I o to, czy krótka sukienka jest zaproszeniem do gwałtu.
To nie jest literacka fikcja. To codzienność Polek. I to o nich, o nas jest ta książka.""")
    books.add_book(connention, 7, "Krew i popiół", "Jennifer L. Armentrout", "", """Poppy jest Panną. Jej życie jest pełne samotności. Nikt nie może jej dotknąć. Tylko garstka wybrańców może zobaczyć jej twarz albo z nią porozmawiać. Jej egzystencja jest pozbawiona wszelkiej przyjemności. Poświęcona bogom, ma tylko jedno zadanie - przygotować się do Ascendencji, rytuału, który ma zapoczątkować nową erę.
Jednak Poppy dużo lepiej czuje się w towarzystwie swoich strażników niż dam dworu i kapłanek. Gdyby mogła, mieczem i łukiem broniłaby swoich bliskich przed niebezpieczeństwem zza Zapory. Dobrze wie, jakie potwory kryją się za nią w magicznej mgle. Niestety, nie ma żadnego wpływu na swoją rolę w zbliżającym się obrządku. Mimo to, Poppy jest gotowa podjąć ryzyko.""")
    books.add_book(connention, 8, "Gdzie śpiewają raki", "Delia Owens", "978-83-8139-268-6", """Pogłoski o Dziewczynie z Bagien latami krążyły po Barkley Cove, sennym miasteczku u wybrzeży Karoliny Północnej. Dlatego pod koniec 1969 roku, gdy na mokradłach znaleziono ciało przystojnego Chase’a Andrewsa, miejscowi zwrócili się przeciwko Kyi Clark, zwanej Dziewczyną z Bagien.
Lecz Kya nie jest taka, jak o niej szepczą. Wrażliwa i inteligentna, zdołała sama przetrwać wiele lat na bagnach, które nazywa domem, choć jej ciało tęskniło za dotykiem i miłością. Przyjaźni szukała u mew, a wiedzę czerpała z natury. Kiedy dzikie piękno dziewczyny intryguje dwóch młodych mężczyzn z miasteczka, Kya otwiera się na nowe doznania — i dzieją się rzeczy niewyobrażalne.
Gdzie śpiewają raki to wysmakowana oda do świata przyrody, wzruszająca fabuła o dojrzewaniu i zaskakująca relacja z procesu. Owens przypomina, że dzieciństwo nas kształtuje definitywnie i że wszyscy bez wyjątku podlegamy wspaniałym, lecz nieokiełznanym sekretnym siłom natury.""")
    books.add_book(connention, 9, "27 śmierci Toby’ego Obeda", "Joanna Gierak-Onoszko", "", """To też jest Kanada: siedem zapałek w słoiku, sny o czubkach drzew, powiewające na wietrze czerwone suknie, dzieci odbierane rodzicom o świcie. I ludzie, którzy nie mówią, że są absolwentami szkół z internatem. Mówią: jesteśmy ocaleńcami. Przetrwaliśmy.
– Zniszczono cały nasz naród. Nigdyśmy się nie podnieśli. W Europie ekscytujecie się modą na Kanadę, bo patrzycie na nią przez kolorowe skarpetki naszego nowoczesnego premiera. Ale prawda mniej się nadaje do lajkowania – powiedział autorce jeden z bohaterów tej książki.
Joanna Gierak-Onoszko spędziła w Kanadzie dwa lata, sprawdzając, co ukryto pod tamtejszą kulturową mozaiką. W swoim reportażu autorka kreśli obraz Kanady, który burzy nasze wyobrażenia o tym kraju.
Dlaczego Kanada ściąga dziś z pomników i banknotów swoich dawnych bohaterów? Jak to możliwe, że odbierano tam dzieci rodzicom? Czyja ręka temu błogosławiła?
"27 śmierci Toby’ego Obeda" to reporterska opowieść o winie i pojednaniu, zbrodni bez kary i ludziach, którzy wymykają się przeznaczeniu.""")
    books.add_book(connention, 10, "Anomalia", "Hervé Le Tellier", "978-83-961264-8-1", "Na razie brak")
    books.add_book(connention, 11, "Niewybaczalne", "Izabela Janiszewska", "978-83-66981-06-5", """"Zaginione dziecko, niewybaczalna zbrodnia i jedno kłamstwo, które zniszczy wszystko…
Trzyletni chłopiec puszcza rękę mamy i znika bez śladu w domu towarowym. Wkrótce potem śledczy odnajdują na pobliskich łąkach trzy ofiary pewnej przerażającej zbrodni. Odkrycie to paraliżuje miejscową społeczność. Narasta nieufność i panika, a jednocześnie ktoś bardzo stara się, by prawda o morderstwie nie ujrzała światła dziennego.
Dwadzieścia pięć lat później Zuzannę budzi pukanie do drzwi. Na progu zastaje policjantów, którzy informują ją o śmierci ojca. Niebawem okazuje się, że cała przeszłość kobiety została zafałszowana. By zrozumieć tragedię sprzed lat i raz na zawsze przerwać zmowę milczenia, Zuzanna musi udać się w podróż tam, gdzie zaczęła się ta lawina kłamstw.
Jedno kłamstwo wystarczy, by zacząć wątpić we wszystkie prawdy.""")
    books.add_book(connention, 12, "Mama kłamie", "Michel Bussi", "978-83-8139-474-1", """Nic nie jest tak ulotne jak pamięć dziecka.
Gdy trzyipółletni Malone twierdzi, że jego mama nie jest jego prawdziwą mamą, choć wydaje się to niemożliwe, psycholog dziecięcy Vasile wierzy mu. Jako jedyny…
Musi działać szybko. Odkryć prawdę. Szukać pomocy. Wspomnienia Malone’a zaczynają się już bowiem zacierać, zachowane w okruchach pamięci i rozmowach, jakie chłopczyk prowadzi z Gutim, swoją pluszową maskotką.
Rozpoczyna się odliczanie. Aż do chwili, gdy wszystko się zmieni. Do chwili, gdy machina pójdzie w ruch i maski opadną.
Kim jest Malone?""")
    books.add_book(connention, 13, "Monachium", "Robert Harris", "978-83-8125-253-9", """Opowieść o lojalności i zdradzie, osnuta wokół brzemiennej w skutki konferencji monachijskiej z 1938 roku.
Świat staje na krawędzi wojny. To ostatnia szansa, by zmienić historię...
Wrzesień 1938 roku. Hitler za wszelką cenę chce rozpocząć wojnę. Brytyjski premier Chamberlain desperacko próbuje utrzymać pokój. Wszystko rozstrzygnie się w mieście, które już zawsze będzie kojarzyło się z tym wydarzeniem: Monachium.
Podczas gdy samolot z Chamberlainem na pokładzie leci nad kanałem La Manche, z Berlina do Bawarii zmierza pociąg z Führerem. Wśród osób towarzyszących premierowi Wielkiej Brytanii jest jego dobrze zapowiadający się prywatny sekretarz, Hugh Legat. W pociągu zaś jedzie niemiecki dyplomata należący do niewielkiej grupy spiskujących przeciwników Hitlera. Kiedyś studiowali razem w Oksfordzie, lecz przed sześcioma laty ich drogi się rozeszły. Teraz przyszłość Europy zależy od tego, czy znowu się skrzyżują. I czy w sytuacji, w której gra toczy się o najwyższą stawkę, dopuszczą się zdrady. Staną po stronie przyjaciół, rodziny, kraju czy swoich przekonań?""")
    # TODO: KRYMINAŁY

    books.add_book(connention, 14, "Czarna lista", "Holly Seddon", "978-83-8139-588-5", """Gratulacje, ktoś chce, abyś umarł.
 
Gdy Greg, mąż Marianne, ginie w wypadku, kiedy jedzie rowerem do pracy, musi ona uporządkować pozostawiony przez niego świat. Oszalała z rozpaczy, przeszukuje laptop męża. Czytanie jego dawnych mejli ją uspokaja. Przegląda też historię oglądanych przez niego stron. Pewnego dnia odkrywa, że Greg wchodził na strony dark web.
 
Dlaczego szanowany pracownik organizacji charytatywnej i oddany mąż logował się na strony, które obrazują skrajne okrucieństwo ludzi? Strony, gdzie wszystko jest możliwe, wystarczy tylko podać cenę? Marianne bierze głęboki oddech i się loguje... Przeszukuje dane i odnajduje na liście ofiar zabójcy swoje nazwisko.
 
Zaczyna się bać. Nie wie, czy Greg chronił ją, czy też należał do spisku osób, które chcą ją zamordować. Zgłębia ten świat, który tak wciągnął Grega. Podejrzewa, że mąż został zmuszony do robienia niemoralnych rzeczy, aby ją chronić. Że uległ szantażowi.
Wdaje się w niebezpieczną rozgrywkę z mordercą, który otrzymał na nią zlecenie.""")
    books.add_book(connention, 15, "Receptura wszechmocy", "Łukasz Piotrowski", "978-83-8219-583-5", """Wolność to stan umysłu… Co zrobisz, aby ją ocalić?
Życie Łukasza Lijewskiego to przede wszystkim praca – prowadzona przez niego poradnia psychoterapeutyczna cieszy się popularnością, a pacjenci doceniają jego zaangażowanie i empatię. Nikt nie wie o tym, że on sam zmaga się z nerwicą, atakami paniki i przerażającymi snami. Kiedy na prośbę rodziców zgadza się zająć swoją uzależnioną od narkotyków siostrą, przeczuwa, że właśnie pakuje się w potężne tarapaty.
Prawdziwy koszmar zaczyna się jednak w momencie, gdy w jego gabinecie zjawia się dawna przyjaciółka, z którą wiąże go mroczny sekret z przeszłości. On jest na skraju załamania nerwowego, ona ma ambitny plan i zamierza go zrealizować bez względu na konsekwencje… Łukasz szybko się orientuje, że wysunięta przez nią propozycja współpracy to w gruncie rzeczy ultimatum.""")
    books.add_book(connention, 16, "Cena wolności. Kamień węgielny", "Darek W. Tokarski", "", """Żadna rewolucja nie może obyć się bez ofiar...
Doktor Laura Wheepingdoe jest cenioną oceanografką, która od lat próbuje zrozumieć język delfinów. Niespodziewanie okazuje się, że jej pracą oraz okazem, z którym łączy ją wyjątkowa więź, interesują się podejrzani ludzie. Gdy podczas badań w Maroku zostaje porwana, na pomoc rusza jej pułkownik Dąbrowski. Jego superinteligentny komputer pozwala mu wkrótce wpaść na trop skomplikowanej, międzynarodowej intrygi. Wszystko wskazuje na to, że zamieszani są w nią masoni, iluminaci, templariusze, Kościół katolicki, a także… Tadeusz Kościuszko. Niewiarygodne teorie spiskowe nabierają coraz bardziej realnych kształtów, a odkrywanie kolejnych tajemnic grozi śmiertelnym niebezpieczeństwem…""")
    books.add_book(connention, 17, "Mężczyźni, którzy nienawidzą kobiet", "Stieg Larsson", "978-83-65509-56-7", """Pewnego wrześniowego dnia w 1966 roku szesnastoletnia Harriet Vanger znika bez śladu. Prawie czterdzieści lat później Mikael Blomkvist - dziennikarz i wydawca magazynu "Millennium" otrzymuje nietypowe zlecenie od Henrika Vangera - magnata przemysłowego, stojącego na czele wielkiego koncernu. Ten prosi znajdującego się na zakręcie życiowym dziennikarza o napisanie kroniki rodzinnej Vangerów. Okazuje się, że spisywanie dziejów to tylko pretekst do próby rozwiązania skomplikowanej zagadki. Mikael Blomkvist, skazany za zniesławienie, rezygnuje z obowiązków zawodowych i podejmuje się niezwykłego zlecenia. Po pewnym czasie dołącza do niego Lisbeth Salander - młoda, intrygująca outsiderka i genialna researcherka. Wspólnie szybko wpadają na trop mrocznej i krwawej historii rodzinnej.""")
    books.add_book(connention, 18, "Kod Leonarda da Vinci", "Dan Brown", "978-83-66512-47-4", """Jacques Saunière, kustosz Luwru, zostaje zamordowany. Francuska policja o pomoc w śledztwie zwraca się do Roberta Langdona, specjalisty od symboli. Okazuje się, że na miejscu zbrodni znajduje się wiele śladów, które mogą pomóc w ustaleniu zabójcy, ale też stanowią klucz do jeszcze większej zagadki − niezwykłej tajemnicy sięgającej korzeniami początków chrześcijaństwa.
Langdon podejrzewa, że zamordowany był członkiem Zakonu Syjonu, powstałego w 1099 roku tajnego stowarzyszenia strzegącego miejsca ukrycia bezcennej, zaginionej przed wiekami relikwii Kościoła − Świętego Graala. Do organizacji należeli m.in. Leonardo da Vinci i Isaac Newton. Kustosz poświęcił życie, by strzeżony przez zakon sekret nie ujrzał światła dziennego. Kluczowe elementy zagadki kryją się w najsłynniejszych obrazach mistrza Renesansu – Mona Lizie i Ostatniej wieczerzy. Czy ścigany przez policję i bezlitosnego zabójcę Langdon zdoła ujść pogoni i dotrzeć do szokującej prawdy? Jego jedynym sprzymierzeńcem jest piękna Sophie Neveu, agentka policji, specjalistka od tajnych kodów i szyfrów oraz… wnuczka Saunière’a.""")
    books.add_book(connention, 19, "Anioły i demony", "Dan Brown", "978-83-66512-42-9", """Robert Langdon zostaje pilnie wezwany do położonego koło Genewy centrum badań jądrowych CERN. Jego zadanie – zidentyfikować zagadkowy wzór wypalony na ciele zamordowanego fizyka. Langdon ze zdumieniem stwierdza, że jest to symbol tajemnego bractwa iluminatów – potężnej, aczkolwiek nieistniejącej od czterystu lat organizacji walczącej z Kościołem, do której należały najświetniejsze umysły Europy, chociażby Galileusz. Jak się okazuje, iluminaci przetrwali w ukryciu do czasów współczesnych i planują straszliwą wendetę – wysadzenie Watykanu przy użyciu antymaterii wykradzionej z genewskiego laboratorium. Langdon i Vittoria Vetra, córka zamordowanego fizyka, mają zaledwie dobę, by odnaleźć utajnioną od XVI wieku siedzibę iluminatów i zapobiec niewyobrażalnej tragedii. Czy zdołają na czas rozszyfrować wskazówki zapisane w jedynym zachowanym w archiwach Świętego Miasta egzemplarzu legendarnego traktatu Galileusza? Jak zakończy się dramatyczny wyścig z czasem – po tajemnych kryptach i katakumbach, wyludnionych katedrach, tropem symboli iluminatów zakamuflowanych przed wiekami miejscach znanych każdemu mieszkańcowi Rzymu? Zagadka goni zagadkę, prowadząc do najbardziej nieoczekiwanego finału.""")

    # TODO: fantastyka
    books.add_book(connention, 20, "Okrutny Książę", "Holly Black", "978-83-7686-724-3", """Krwawa zbrodnia na zawsze odmienia los trzech sióstr. Zostają porwane do świata elfów, bajecznego Elysium. Upływa dziesięć lat; Jude pragnie za wszelką cenę odnaleźć swoje miejsce w krainie elfów – lecz dumni elfowie gardzą śmiertelniczką, a wzgardliwszy od innych jest książę Cardan, najmłodszy i najokrutniejszy z potomków Najwyższego Króla.

By zdobyć pozycję na Dworze, musi rzucić Cardanowi wyzwanie – a następnie ponieść konsekwencje.

Jude poznaje labirynt intryg i ułudy, odkrywa własną przebiegłość i to, że zdolna jest zadać ból a nawet śmierć. Gdy za sprawą zdradzieckich knowań elfowym dworom zagraża niebezpieczeństwo pogrążenia się w chaosie krwawej wojny, Jude gotowa jest narazić życie, by ocalić siostry i Królestwo.

Pierwsza część trylogii o podstępach i żądzy władzy, czarach i magii – razem z Jude odkrywamy misterną sieć elfowych intryg.""")
    books.add_book(connention, 21, "Dwór srebrnych płomieni. Część 1", "Sarah J. Maas", "978-83-280-9283-9", """Nesta Archeron od zawsze była dumna, wybuchowa i niezbyt skłonna do wybaczania. Odkąd zmuszono ją do wejścia do Kotła i została Fae wbrew swojej woli, walczy o znalezienie własnego miejsca dla siebie w zabójczym i niebezpiecznym świecie. Co gorsza, wojna i wszystko, co w niej straciła, wypaliły w jej duszy niezatarte piętno.

Jedyną osobą, która rozpala ją bardziej niż ktokolwiek inny, jest Kasjan, tajemniczy i twardy wojownik na Dworze Nocy Rhysanda i Feyry. Między Nestą a Kasjanem płonie prawdziwy ogień. Żar jednak może spalić lub oczyścić.

Tymczasem zdradzieckie ludzkie królowe, które powróciły na kontynent podczas ostatniej wojny, zawarły nowy niebezpieczny sojusz, zagrażający kruchemu pokojowi, który zapanował w królestwach. Klucz do powstrzymania kolejnej wojny dzierżą wspólnie właśnie Nesta i Kasjan. By jednak ocalenie pokoju było możliwe, te dwa żywioły muszą zacząć ze sobą współpracować. Czy będzie to możliwe?""")

    books.add_book(connention, 22, "Wiedźmin Sezon burz", "Andrzej Sapkowski", "", """Oto nowy Sapkowski i nowy wiedźmin. Mistrz polskiej fantastyki znowu zaskakuje. Sezon burz nie opowiada bowiem o młodzieńczych latach białowłosego zabójcy potworów ani o jego losach po śmierci/nieśmierci kończącej ostatni tom sagi.
Nigdy nie mów nigdy! W powieści pojawiają się osoby doskonale czytelnikom znane, jak wierny druh Geralta bard i poeta Jaskier oraz jego ukochana, zwodnicza czarodziejka Yennefer, ale na scenę wkraczają też dosłownie i w przenośni postaci z zupełnie innych bajek. Ludzie, nieludzie i magiczną sztuką wyhodowane bestie. Opowieść zaczyna się wedle reguł gatunku: od trzęsienia ziemi, a potem napięcie rośnie. Wiedźmin stacza morderczą walkę z drapieżnikiem, który żyje tylko po to, żeby zabijać, wdaje się w bójkę z rosłymi, niezbyt sympatycznymi strażniczkami miejskimi, staje przed sądem, traci swe słynne miecze i przeżywa burzliwy romans z rudowłosą pięknością, zwaną Koral. A w tle toczą się królewskie i czarodziejskie intrygi. Pobrzmiewają pioruny i szaleją burze. I tak przez 404 strony porywającej lektury.""")
    books.add_book(connention, 23, "Ziemiomorze", "Ursula K. Le Guin", "", """„Ziemiomorze” Ursuli K. Le Guin to jeden z najznakomitszych cykli literatury fantasy, porównywany z dziełami J.R.R. Tolkiena czy C.S. Lewisa. Opisuje malowniczy świat pełen wysp, smoków i tajemnic, w którym najważniejsza jest równowaga między tworzącymi go siłami. Głównym bohaterem serii jest czarnoksiężnik Ged; poszczególne części opowiadają jego losy – od najmłodszych lat i pierwszych kroków stawianych w świecie magii, aż po czasy gdy zaczęła się ona stawać niebezpiecznym narzędziem w rękach zła.
Ged, którego Ziemiomorze na zawsze zapamięta jako Krogulca, zostaje wysłany na wyspę Roke, aby tam zgłębiać czarnoksięską sztukę. Jest obdarzony niezwykłymi magicznymi zdolnościami, więc po latach nauki zostaje Arcymagiem, który będzie musiał pomóc Najwyższej Kapłance Archipelagu – Tenar – uciec z labiryntu ciemności.
Niestety, wraz z upływem lat równowaga Ziemiomorza zacznie się chwiać coraz bardziej, a prawdziwa magia i pradawne zwyczaje coraz częściej wykorzystywane będą przez mroczne siły zła i śmierci…""")
    books.add_book(connention, 24, "Hobbit, czyli tam i z powrotem", "J.R.R. Tolkien", "", """Hobbit to istota większa od liliputa, mniejsza jednak od krasnala. Fantastyczny, przemyślany do najdrobniejszych szczegółów świat z powieści Tolkiena jest również jego osobistym tworem, a pod barwną fasadą nietrudno się dopatrzyć głębszego sensu i pewnych analogii do współczesności.""")
    books.add_book(connention, 25, "Władca Pierścieni", "J.R.R. Tolkien", "", """W zamierzchłych czasach kowale elfów wykuli Pierścienie Mocy. Lecz Mroczny Władca, stworzył w tajemnicy Jedyny Pierścień, aby rządził pozostałymi. Ale Pierścień zniknął na wiele wieków w Śródziemiu, zanim trafił w ręce hobbita, którego przeznaczeniem stało się jego zniszczenie...
W tej książce Tolkien powołał do życia swoją niezwykłą krainę fantazji: oszałamiający świat Śródziemia. Pełny kształt nadał mu 17 lat później w trylogii „Władca Pierścieni” – fantastycznej epopei, jedynej w swoim rodzaju powieści przygodowej osnutej na starożytnej legendzie i z głębokim wydźwiękiem etycznym. Ogniwem łączącym obie książki jest Pierścień. „W Hobbicie” to po prostu magiczny przedmiot, we „Władcy Pierścieni” – już potężne narzędzie zła decydujące o losach świata. Świata, dla którego ratunkiem staje się nie siła umysłu czy oręża, lecz zwykły odruch serca, czysto ludzka – choć uosabiana przez hobbita – zdolność do okazania miłosierdzia.""")
    books.add_book(connention, 26, "Eragon", "Christopher Paolini", "978-83-66409-00-2", """Eragon – młody, wiejski chłopak znajduje niebieski kamień i przynosi go do domu. Ale zanim udaje mu się sprzedać go handlarzowi, z kamienia wykluwa się szafirowy smok, Saphira. Smoka próbuje ukraść zły Urgals, który brutalnie morduje wuja Eragona. Chłopcu i smoczycy w ostatniej chwili udaje się uciec. Od tej chwili Eragon poprzysięga zemstę mordercy wuja i wyrusza na wyprawę, by uratować świat i stać się ostatnim legendarnym Jeźdźcem Smoków.
Poczekajcie, to nie wszystko.
Eragon jest związany z Saphirą magiczną mocą, psychiczną więzią, która wzmacnia ich wzajemną siłę, lecz jest trochę… nieprzewidywalna. Król krainy, w której rozgrywa się akcja – Alagaesii – jest także Jeźdźcem, zaprzedał się jednak ciemnej mocy…""")
    books.add_book(connention, 27, "Najstarszy", "Christopher Paolini", "978-83-66409-01-9", """Zapada mrok… w sercach wzbiera rozpacz… zło triumfuje… Zaledwie kilka dni temu Eragon i jego smoczyca Saphira ocalili kryjówkę buntowników przed atakiem wojsk króla Galbatorixa, okrutnego władcy imperium. Teraz muszą udać się do Ellesméry, krainy elfów, gdzie Eragona czeka dalsze szkolenie. Musi nauczyć się jeszcze lepiej władać bronią Smoczych Jeźdźców: mieczem i magią.
Wyrusza zatem w najważniejszą podróż swego życia, poznaje nowe cudowne miejsca i nowych kompanów, przeżywa nowe przygody. Jednakże cały czas towarzyszą mu chaos i zdrada, i nic nie jest takie, jakie się wydaje. Wkrótce Eragon nie wie już, komu może zaufać. Tymczasem jego kuzyn Roran musi stoczyć własną bitwę – bitwę, która być może narazić Eragona na jeszcze większe niebezpieczeństwo. Czy mroczna ręka króla zdławi wszelki opór? Z tego starcia Eragon może nie ujść z życiem…""")
    books.add_book(connention, 28, "Brisingr", "Christopher Paolini", "978-83-66409-02-6", """Eragon i jego smoczyca Saphira ledwie uszli z życiem z ogromnej bitwy z wojownikami Imperium na Płonących Równinach. Teraz muszą stawić czoło kolejnym niebezpieczeństwom – a także splątanej sieci obietnic i przysiąg, których Eragon może nie zdołać dotrzymać.
Pierwsza to obietnica złożona kuzynowi Roranowi, że pomoże ocalić z niewoli u króla Galbatorixa jego ukochaną Katrinę. Jednakże Eragon musi pozostać lojalny także wobec innych. Vardeni rozpaczliwie potrzebują jego siły i zdolności, podobnie elfy i krasnoludy. Gdy buntownicy zaczynają szemrać, a ze wszystkich stron zagrażają im wrogowie, Eragon musi dokonać wyborów, które zawiodą go na krańce Imperium i jeszcze dalej i mogą wymagać niewyobrażalnie wielkich ofiar.
Eragon to największa nadzieja wolnych ludów na zakończenie tyranii Galbatorixa. Czy niegdysiejszy chłopak ze wsi zdoła zjednoczyć siły buntowników i pokonać króla?""")
    books.add_book(connention, 29, "Dziedzictwo", "Christopher Paolini", "978-83-66409-03-3", """Do niedawna Eragon, Smoczy jeździec, był biednym synem farmera, a jego smoczyca Saphira jedynie błękitnym kamieniem w lesie. Długie miesiące treningów i bitew przyniosły zwycięstwa i nadzieję, ale także wielkie straty. Mimo to najważniejsza bitwa ciągle przed nimi: czeka ich ostateczna rozgrywka z Galbatoriksem.
Kiedy to już nastąpi, będą musieli być wystarczająco silni, by go pokonać. Bo jeśli nie oni, nikt nie podoła temu zadaniu. Nie będzie też drugiej szansy.Smok i jego jeździec zaszli dalej, niż ktokolwiek mógł przypuszczać, ale czy uda się im obalić złego króla i przywrócić sprawiedliwość w Alagaësii. I jeśli nawet, to za jaką cenę?
Nadzwyczajne uwieńczenie bestsellerowego cyklu Dziedzictwo.""")


    # TODO: przygodowe
    books.add_book(connention, 30, "W pustyni i w puszczy", "Henryk Sienkiewicz", "978-83-65875-72-3", """Pełna przygód i zwrotów akcji historia dwójki dzieci – Stasia i Nel – i ich wędrówki po Czarnym Lądzie wciąż porusza serca i działa na wyobraźnię.""")
    books.add_book(connention, 31, "W 80 dni dookoła świata", "Juliusz Verne", "978-83-65634-51-1", """Kolejny tytuł w znakomitej serii "Klasyka światowej literatury", która obejmuje prawdziwe perły literatury dziecięcej i młodzieżowej. Klasyczne opowieści okraszone ilustracjami współczesnych polskich ilustratorów i wydane w poręcznym formacie, to idealny pomysł na spędzenie czasu ze światowego formatu literaturą i znakomite uzupełnienie domowej biblioteki.""")
    books.add_book(connention, 32, "Wyspa skarbów", "Robert Louis Stevenson", "978-83-8091-549-7", """Wielokrotnie ekranizowana i tłumaczona powieść, szkolnego kolegi Artura Conana Doyle’a, dopisana do rysunku pirackiej mapy, elektryzując rzesze czytelników przeszła do klasyki gatunku powieści awanturniczej, a stworzony przez Stevensona wizerunek pirata stał się wzorem, inspirującym kolejne pokolenia twórców. Kto bowiem nie marzy o podróży życia i odkrywaniu nowych lądów?
Andrzej Polkowski, znany m.in. z przekładów Opowieści wigilijnej, Księgi dżungli, Opowieści z Narnii oraz cyklu o Harrym Potterze, przybliża współczesnym czytelnikom barwny świat piratów, który nie zestarzał się z upływem czasu. Świeży i plastyczny przekład uzupełniają malarskie ilustracje Roberta Innocentiego, laureata Nagrody im. H. Ch. Andersena, zwanej małym Noblem. Twórczy duet Polkowski i Innocenti zaprasza na pokład nowych czytelników, dowodząc w treści i formie, iż fabuła Stevensona, nie straciła nic ze swej atrakcyjności.""")
    books.add_book(connention, 33, "Ruiny Gorlanu", "John Flanagan", "", """Korpus Zwiadowców to najbardziej elitarna formacja w Królestwie Araluenu. Zwiadowcy, poza wypełnianiem misji wywiadowczej, są wyśmienitymi strategami i najlepszymi łucznikami. To im król ufa najbardziej i powierza im trudne zadania, w których muszą się wykazać nie tylko męstwem, niezłomnością i inteligencją, ale też lojalnością wobec władcy oraz dyskrecją. Ale nie tylko zwiadowcy są wyjątkowi. Ich konie są najbardziej wytrzymałymi wierzchowcami w całej armii i choć niewielkie, sprawdzają się w trudnych warunkach terenowych i wbrew pozorom w bezpośrednim starciu. Wyróżniają się też nieprzeciętnym rozumem, krążą plotki, że potrafią rozmawiać ze swoim panem, opiekunem i przyjacielem – zwiadowcą.
Bohaterem książki jest piętnastoletni sierota, Will, którego ojciec, odważny wojownik, zginął bohaterską śmiercią w starciu wojsk Araluenu ze zdrajcą, baronem Morgarathem.
Will od najwcześniejszych lat marzy, by zostać rycerzem… Problem w tym, że do Szkoły Rycerskiej przyjmują młodzieńców silnych, muskularnych i dobrze zbudowanych. A Will, cóż, nie dość, że niski, to jeszcze chudy. Za to szybko ucieka.
Już wydaje się, że chłopak będzie musiał zostać po prostu rolnikiem, gdy nagle na scenie pojawia się tajemniczy Halt – zwiadowca. I on jeden spośród mistrzów szkół decyduje się przyjąć Willa na ucznia. Jest szalenie wymagający, zgryźliwy i humorzasty, ale po pewnym czasie Will skoczyłby za swoim mistrzem w ogień.""")
    books.add_book(connention, 34, "Ziemia skuta lodem", "John Flanagan", "", """Trzeci tom bestsellerowej sagi dla młodzieży pióra australijskiego pisarza Johna Flanagana.
Po spaleniu mostu, przez który Morgarath chciał przeprowadzić armię na ziemie Araluenu, Will i Evanlyn trafiają do niewoli. Porwani przez Skandian pod dowództwem budzącego postrach Eraka, odpływają na nieznane północne ziemie.
Halt poprzysiągł ocalić Willa i uczyni wszystko, by dotrzymać obietnicy – nawet jeśli przyjdzie mu okazać niesubordynację i złamać rozkazy króla. W korpusie zwiadowców nie ma jednak miejsca dla tych, którzy kierują się własnym interesem! Pozbawiony wsparcia, odrzucony przez towarzyszy, Halt wyrusza na niebezpieczną wyprawę do odległej, skutej lodem Skandii. Towarzyszy mu najlepszy przyjaciel Willa – Horace, którego niezwykłe szermiercze zdolności mogą się bardzo przydać na dzikich i nieprzystępnych terenach, przez które przyjdzie im podróżować. Ale budzące zachwyt i grozę umiejętności młodego rycerza ściągają na mężczyzn uwagę okolicznych lordów… Czas biegnie nieubłaganie. Czy Halt i Horace oszczędzą Willowi losu niewolnika?""")
    books.add_book(connention, 35, "Był sobie pies", "W. Bruce Cameron", "978-83-66338-47-0", """Oto pełna głębokich uczuć i zdumiewająca opowieść o oddanym psie, który życiową misją czyni wpajanie swoim opiekunom znaczenia miłości i pogody ducha. To powołanie wypełnia na przestrzeni... kilku żyć.
Bailey jest zszokowany – po krótkim i smętnym życiu, jakiego doświadczył w postaci bezpańskiego kundla, odradza się w ciele niesfornego szczeniaka. Kiedy trafia pod opiekę ośmiolatka Ethana, który kocha go całym sercem, odkrywa nowe oblicze – dobrego, poczciwego psiaka. Jednak życie u uwielbianej rodziny to nie koniec przygód Baileya. Ponownie odradza się w postaci kolejnego psa!
"Był sobie pies" to pokrzepiająca i pomysłowa historia. Doprowadza czytelnika do skrajnych emocji – jest jednocześnie uroczo zabawna i dotkliwie przejmująca. Ta książka w piękny sposób pokazuje, że miłość nie zna granic oraz że nasi najbliżsi zawsze są przy nas. Najważniejsze przesłanie powieści głosi, że każda istota na ziemi urodziła się z misją.
Wszystkie psy idą do nieba... Chyba że mają niedokończone sprawy na Ziemi.""")
    books.add_book(connention, 36, "Był sobie pies 2", "W. Bruce Cameron", "978-83-66338-74-6", """Wszystkie psy doskonale wiedzą, że życie ma sens tylko u boku ukochanego człowieka
Bailey – bohater bestsellera „Był sobie pies” – powraca w nowym psim wcieleniu, aby wypełnić kolejną misję!
Mała Clarity June opuszcza ukochaną babcię i jej psa i wyjeżdża z matką do wielkiego miasta. Psiak przeżył już wiele żyć i sporo się nauczył o ludziach. Miał różne imiona: Bailey, Toby, Ellie, Koleżka…
Bailey powraca w nowym wcieleniu na czterech łapach i spotyka dorastającą Clarity. Wie, że jego misja jeszcze nie została wypełniona – musi pilnować i strzec dziewczynki. Musi być dzielnym psem!
Tym razem zrobi wszystko, aby pomóc ukochanej pani odnaleźć prawdziwą miłość i zrealizować jej marzenia. Czasami będzie musiał odejść, by zaraz znów powrócić jako inny psi przyjaciel. Bo jedno wie na pewno: życie jest na tyle pomerdane, że zawsze warto trzymać się razem""")
    books.add_book(connention, 37, "O psie, który dał słowo", "W. Bruce Cameron", "", """Nowa książka autora najbardziej rozmerdanych opowieści!
Dla fanów bestsellera „Był sobie pies” W. Bruce’a Camerona.
Na Baileya, psa o wielu wcieleniach, którego pokochały setki tysięcy dzieci i dorosłych, czeka bardzo ważne zadanie. Tym razem nie będzie pamiętał swoich poprzednich żyć, ale nie będzie sam! Dołączy do niego urocza psina Lacey, z którą wspólnie postarają się dotrzymać psiego słowa. Burke to bardzo uzdolniony chłopiec, który jeździ na wózku. Kiedy przestanie rosnąć, będzie mógł poddać się operacji. Jednak do tego czasu potrzebuje wsparcia silnego psa, który pomoże mu w codziennych czynnościach. Ktoś tu będzie miał łapy pełne roboty!""")
    books.add_book(connention, 38, "Tomek na Czarnym Lądzie", "Alfred Szklarski", "978-83-287-1117-4", """Chwilowo brak.""")
    books.add_book(connention, 39, "Tomek w krainie kangurów", "Alfred Szklarski", "978-83-8114-507-7", """Akcja "Tomka w krainie kangurów" zaczyna się w 1902 roku, kiedy Polska znajduje się pod zaborami. Tomek Wilmowski, syn rewolucjonisty, uczeń warszawskiego gimnazjum, opór przeciwko caratowi ma właściwie we krwi. Opiekunowie bojąc się o niego, korzystają z nadarzającej się okazji i wysyłają Tomka do ojca przebywającego na emigracji. Obaj mają udać się na łowy do Australii. I tu nasz bohater przeżywa niecodzienne przygody w scenerii egzotycznej przyrody. A wszystko to jest opisane ciekawie i z pasją.""")
    books.add_book(connention, 40, "Zew krwi", "Jack London", "", """"Zew krwi" to jedna z najbardziej znanych i poczytnych powieści Jacka Londona. Wielokrotnie trafiała na srebrny ekran. Bohaterem powieści jest pies Buck – mieszaniec bernardyna i owczarka szkockiego – który wiódł spokojne życie u boku kochającego pana. Pewnej nocy został porwany i sprzedany. Trafił na Alaskę w czasach gorączki złota i rozpoczął walkę o przetrwanie.""")

    # TODO: romans
    books.add_book(connention, 41, "Pokochaj albo zabij", "Weronika Ancerowicz", "978-83-8178-753-6", """Czasem największe potwory nie skrywają się pod łóżkiem, tylko śpią tuż obok.
Isabelle Rodriguez od dziecka była przygotowywana do roli, którą wyznaczył jej ojciec. Jako córka mafiosa musiała wcześniej czy później zacząć działać na rzecz rodziny. Więc kiedy kończy dwadzieścia jeden lat i otrzymuje pierwsze poważne zadanie, jest wniebowzięta.
Jej ambitny, bardzo potężny ojciec chce poszerzyć wpływy o Nowy Jork. Isabelle musi rozpracować całe podziemie narkotykowe w mieście. W końcu odkrywa sieć dilerów i trafia na ważny trop, który prowadzi do klubu „Rising Sun”. Kobieta czuje, że właśnie w tym miejscu znajdzie odpowiedzi dla swojego ojca.
Przez przypadek poznaje tam tajemniczego mężczyznę. Nieznajomy ją fascynuje, więc postanawia się do niego zbliżyć. Isabelle podejrzewa, że może on mieć coś wspólnego z mafijnym rynkiem narkotykowym.
Alessandro Salvatore szybko udowodni Isabelle, że życie, jakie do tej pory znała, wcale nie było trudne. I pokaże, jak bardzo się myliła, nie dostrzegając w mężczyźnie niebezpieczeństwa oraz jego mrocznej natury.""")
    books.add_book(connention, 42, "Zdławienie", "Lauren Asher", "978-83-66429-33-8", """Maya
Moje plany po studiach obejmują: vlogowanie, picie w różnych miejscach świata i wyjazdy z bratem, który bierze udział we wszystkich Grand Prix Formuły 1. Nie był w nich uwzględniony playboy Noah Slade, Mistrz Świata F1. Jego wrażliwość zaskakuje mnie, zniewala i zamyka moje serce dla każdego mężczyzny, który ośmieliłby się pojawić po nim. Nie ma sensu prosić o jego zwrot, bo wiem, że zanim uda mi się je odzyskać, zostanie roztrzaskane w drobny mak.
Noah
Jestem jedynym synem legendy Formuły 1, a fani nazywają mnie Amerykańskim Księciem. Żyję po to, by po wyścigu stać na najwyższym stopniu podium, przed tłumami skandującymi moje imię, z szampanem cieknącym po twarzy i adrenaliną buzującą w żyłach. Kobiety chcą ze mną sypiać, mężczyźni pragną mną być. Jednak nikt nie rzuca mi większego wyzwania niż Maya Alatorre, siostra mojego rywala i nowego członka zespołu. Razem tworzymy tykającą bombę i wystarczy jeden niewłaściwy ruch, by doszło do wybuchu. Ale przy niej chcę podpalić lont, eksplodować wspólnie w pasji i bólu. Bo, koniec końców, w pożądaniu i na wojnie wszystkie chwyty są dozwolone.""")
    books.add_book(connention, 43, "Zderzenie", "Lauren Asher", "978-83-66429-54-3", """Sophie Mitchell
Liam to złoty chłopiec Formuły 1, lecz cały jego wizerunek został zbudowany na kłamstwie. Tak się złożyło, że ten czarujący i przebiegły mężczyzna obiecał mi pomóc z realizacją listy rzeczy, które chciałabym zrobić w życiu. Niepewna własnych uczuć próbuję oddzielić nas bezpieczną granicą przyjaźni, ale Liam stanowczo stara się ją pokonać i proponuje nieco inny układ.
Jeden sezon. Jedna lista. Jeden nieprzyzwoity sekret.
Liam Zander
Sophie jest urzeczywistnieniem moich najśmielszych fantazji, a jednocześnie zagrożeniem dla nowego kontraktu. Należy do przeciwnej drużyny, dlatego powinienem jej unikać za wszelką cenę. I choć początkowo usiłuję… I choć wszyscy są przeciwni naszej przyjaźni… Nie mogę wybić sobie z głowy jej nieprzyzwoitej listy.""")
    books.add_book(connention, 44, "Krok do miłości", "Sylwia Kubik", "978-83-8135-105-8", """W cieniu żuławskich wierzb odnajdziesz miłość
Ewa ma poważne kłopoty. Jednego dnia traci wszystko, co było jej drogie. Nawet jej ukochany wystawia jej walizki za drzwi. Ewa zostaje sama, bez środków do życia i z dużym rachunkiem za pobyt w szpitalu. Gdy już jej się wydaje, że cały świat runął jej z hukiem na głowę, przypomina sobie o domu odziedziczonym po babce i wyjeżdża na Żuławy. Tam stary przyjaciel rodziny oferuje jej pomoc
Czy Ewa w nowym miejscu zapomni o przeszłości i zacznie czerpać radość z życia?
Czy Kamil, młody właściciel gospody, w której dziewczyna znajduje zatrudnienie, zawalczy o jej uczucie mimo sprzeciwu rodziny? A może jej serce zdobędzie Antek?
„Krok do miłości” to wzruszająca i pełna ciepła opowieść o odnajdywaniu siebie i swojego miejsca na ziemi. Jeśli tylko odważysz się być sobą, szczęście i miłość upomną się o ciebie na najbliższym zakręcie.""")
    books.add_book(connention, 45, "Tajemnica z przeszłości", "Sylwia Kubik", "978-83-8135-113-3", """Nikt nie stanie ci na drodze do prawdziwej miłości
Ewa zakochuje się w Kamilu, rozważa nawet, czy z nim nie zamieszkać. Mimo to Antek dalej wytrwale zabiega o jej względy.
Szczęście zakochanych zakłóca niespodziewany przyjazd dawnej znajomej Ewy, Agnieszki, która prosi ją o pomoc. Ewa chce zerwać z przeszłością – dlatego odmawia. Jednak Agnieszka zaczyna ją szantażować. I Ewa ze strachu ulega.
Czy sekret, które chce wyjawić Agnieszka, spowoduje, że Ewa i Kamil się rozstaną?
Czy ich miłość przetrwa próbę, którą szykuje dla nich los?
„Tajemnica z przeszłości” to drugi tom pięknej opowieści o miłości, rozgrywającej się w scenerii Żuław.""")
    books.add_book(connention, 46, "W cieniu wierzb", "Sylwia Kubik", "", """Na wybaczenie i na miłość nigdy nie jest za późno.
Czy Ewa i Kamil znajdą w sobie odwagę, by się o tym przekonać?
W końcu nadeszło lato pachnące sianem i zbożem. Dla jednych czas odpoczynku i zabawy, dla innych ciężkiej pracy – i zmierzenia się z problemami. Ewa przekonała się, że uciekanie przed przeszłością sprowadza na nią tylko nieszczęścia. Jej marzenia posypały się jak domek z kart. Musi więc zacząć od nowa budować swoją przyszłość, tym razem na porządnych fundamentach.
Tylko czy można odzyskać utracone zaufanie i dobre imię? Czy można definitywnie zamknąć przeszłość?
"W cieniu wierzb" to trzeci tom historii Ewy, w którym ponownie zajrzysz do kuchni Rozalii i zachwycisz się żuławskimi pejzażami. Zanurzysz się w opowieść o sile miłości, na którą nigdy nie jest za późno. Takiej, która potrafi rozkwitnąć tam, gdzie najmniej się tego spodziewamy.""")
    books.add_book(connention, 47, "Pamiętnik", "Nicholas Sparks", "978-83-8215-238-8", """Karty starego notatnika kryją historię romantycznej miłości. Starszy pan codziennie odczytuje ją mieszkającej w domu opieki kobiecie chorej na alzheimera. Jest to opowieść o bogatej dziewczynie z miasta i ubogim chłopaku z prowincji, których pewnego lata połączyło wyjątkowe uczucie. Wbrew sobie zostali rozdzieleni, a ich miłość wystawiona na próbę. Czy uda im się ponownie spotkać?""")
    books.add_book(connention, 48, "List w butelce", "Nicholas Sparks", "978-83-8125-726-8", """Wyrzucona za burtę butelka mogła trafić w najodleglejszy zakątek świata. Tymczasem fale wyrzuciły ją na plażę w zatoce Cape Cod, gdzie trafiła w ręce Theresy Osborne. W środku był list miłosny zaczynający się od słów: ,,Moja najdroższa Catherine, tęsknię za Tobą, ukochana, tak jak zawsze, ale dzisiaj było mi bardzo ciężko, bo ocean śpiewał o naszym wspólnym życiu". Zaintrygowana historią pary kochanków Theresa rozpoczyna poszukiwania człowieka, który potrafił tak mocno i wiernie kochać.""")
    books.add_book(connention, 49, "Samotność w sieci", "Janusz Leon Wiśniewski", "978-83-8032-181-6", """Książka, która stała się fenomenem. Najbardziej poruszająca powieść o miłości.
Przypadkowe spotkanie w wirtualnej rzeczywistości staje się początkiem wszystkiego. Ona i on – oboje dźwigają bagaż przeszłości, złych decyzji, zmęczenia życiem. I nagle uświadamiają sobie, że wcale nie musi tak być. Wymiana maili i długie rozmowy są jak przebudzenie. Odkrywają siebie nawzajem, a im głębiej się poznają, tym bardziej czują, jak podobne są ich uczucia. Internetowa przestrzeń, która ich dzieli, daje im poczucie bezpieczeństwa. Mogą odkryć prawdę o sobie. Jej nieudane małżeństwo, jego samotność, ich wspólna potrzeba bliskości. Ale miłości nie wystarczą tylko słowa. Czy można bezkarnie połączyć dwie dusze i dwa ciała także w rzeczywistości?""")

    # TODO dramat
    books.add_book(connention, 50, "Ferdydurke", "Witold Gombrowicz", "978-83-8114-483-4", """Chwilowo brak.""")
    books.add_book(connention, 51, "Człowiek w poszukiwaniu sensu", "Viktor E. Frankl", "978-83-8143-356-3", """Człowiek w poszukiwaniu sensu Viktora E. Frankla to jedna z najbardziej wpływowych książek w literaturze psychiatrycznej od czasu Freuda. Zaczyna się od długiego, suchego i głęboko poruszającego osobistego eseju o pięcioletnim pobycie Frankla w Auschwitz i innych obozach koncentracyjnych i jego wysiłkach w tym czasie, by znaleźć powody do życia. Druga część książki opisuje metody psychoterapeutyczne, które Frankl opracował jako pierwszy na bazie swoich doświadczeń z obozów. Freud uważał, że życiem człowieka rządzi popęd seksualny i pokusy. Frankl z kolei wierzy, że najgłębszym popędem człowieka jest poszukiwanie sensu i celu. Logoterapia Frankla zatem bardziej przystaje do zachodnich religii niż freudeowskiej psychoterapii.""")
    books.add_book(connention, 52, "Moralność pani Dulskiej", "Gabriela Zapolska", "978-83-11-14069-1", """Chwilowo brak""")
    books.add_book(connention, 53, "Noc listopadowa", "Stanisław Wyspiański", "", """Trzeci z kolei utwór Stanisława Wyspiańskiego, po „Warszawiance” i „Lelewelu”, poruszający tematykę powstania listopadowego.
Utwór przedstawia obraz pierwszych godzin powstania listopadowego (wydarzenia nocy z 29 na 30 listopada 1830 roku), wspaniałego zrywu podchorążych i jego przebieg.""")
    books.add_book(connention, 54, "Król Edyp", "Sofokles", "978-83-8114-864-1", """Król Edyp Sofoklesa (V wiek p.n.e.), jeden z największych dramatów wszech czasów, przez Arystotelesa uznany za „najpiękniejszą tragedię”, mimo dwóch i pół tysiąca lat, jakie upłynęły od jego powstania, wciąż jest utworem żywym i fascynującym, stale powracającym na scenę.""")
    books.add_book(connention, 55, "Balladyna", "Juliusz Słowacki", "978-83-65875-28-0", """Balladyna to dramat w pięciu aktach, napisany przez Juliusza Słowackiego w epoce romantyzmu. To opowieść o żądzy władzy i rywalizacji. Imię głównej bohaterki – Balladyna – nawiązuje do gatunku literackiego, jakim jest ballada, w której pojawiają się motywy fantastyczne i elementy wierzeń ludowych.
 
Balladyna od lat znajduje się w kanonie lektur szkolnych omawianych na lekcjach języka polskiego.""")
    books.add_book(connention, 56, "Dziady", "Adam Mickiewicz", "978-83-65875-26-6", """Dziady Adama Mickiewicza to jeden z najbardziej znanych utworów w literaturze polskiej i jednocześnie jedno z dzieł najbardziej reprezentatywnych dla polskiego romantyzmu. Od lat regularnie wystawiane na deskach teatrów całej Polski, czytane przez kolejne pokolenia czytelników, inspirujące twórców i niosące wciąż aktualne treści. Każda z części utworu porusza inne tematy, ale razem tworzą spójną wizję świata rządzonego przez niezmienne prawa boskiej sprawiedliwości i miłosierdzia.""")
    books.add_book(connention, 57, "Romeo i Julia", "William Shakespeare", "978-83-66729-96-4", """Chwilowo brak.""")
    books.add_book(connention, 58, "Skąpiec", "Molier", "978-83-66729-98-8", """Harpagon, tytułowy skąpiec, ma dwoje dzieci, Kleanta i Elizę. Kleant zakochany jest w Mariannie, tak samo jak jego ojciec, a Eliza w Walerym. Muszą jednak ukrywać swą miłość ze względu na Harpagona. Marianna mieszka ze swoją chorą matką niedaleko Harpagona. Dziewczyna jest ładna, dobra, uczciwa ale niezbyt bogata, więc Kleant nie może liczyć na przychylność ojca. Walery nie zna swoich rodziców, nie posiada majątku, więc chce się wkraść w łaski Harpagona. Kleant zwierza się siostrze ze swoich uczuć. Nie domyśla się, że Eliza też jest zakochana. U Harpagona przejawia się niespotykanie duża miłość do pieniądza, nigdy o nim nie zapomina.""")

    # TODO: sci-fi
    books.add_book(connention, 59, "Star Wars, Imperium kontratakuje", "Donald F. Glut", "", """Zniszczenie Gwiazdy śmierci nie oznacza końca wojny. Teraz Imperium atakuje bazę rebeliantów na Hoth. Luke, Han Solo i księżniczka Leia zostają zmuszeni do ucieczki, lecz Darth Vader podąża ich śladem...""")
    books.add_book(connention, 60, "Proxima", "Stephen Baxter", "", """XXVII wiek. Przyszłość ludzkości w tej galaktyce wydaje się niemal nieograniczona…
Są w niej setki milionów czerwonych karłów, które posiadają planety nadające się do zamieszkania przez ludzi. Taki właśnie jest świat Proxima Centauri. Dla ludzkości może oznaczać nadzieję na przetrwanie, bo toczące nieustanne wojny między sobą przeludnione kolonie na Marsie i Merkurym z pewnością tego nie gwarantują.
Ale najpierw nowy świat musi zostać skolonizowany, a brakuje chętnych, by zostać osadnikiem. Wyprawa na surową planetę nie zapewni splendoru ani żadnych gratyfikacji, a oferuje tylko trud, samotność, pustkę… Yuri Jones wraz z tysiącem innych przymusowych kolonistów niebawem dowie się, jak to jest żyć w nieprzyjaznym pustynnym świecie, którego połowa skrywa się w wiecznej ciemności.
Proxima opowiada niesamowitą historię kolonizacji surowego nowego Edenu, a tajemnica, którą skrywa ten świat, na zawsze zmieni postrzeganie naszej roli we wszechświecie.""")
    books.add_book(connention, 61, "Obelisk", "Stephen Baxter", "", """Chwilowo brak""")
    books.add_book(connention, 62, "Ultima", "Stephen Baxter", "", """Fascynująca powieść science fiction o eksploracji alternatywnych wszechświatów i głębokich otchłani czasu.
Na planecie Per Ardua krążącej wokół gwiazdy Proxima odkryto artefakty obcych – Włazy, które pozwalają ludziom pokonywać lata świetlne, jakby wkraczali do innego pokoju. Ale ta nowo odkryta łatwość podróżowania w przestrzeni ma konsekwencje….
Gdy ludzkość odkrywa prawdziwą naturę wszechświata, ujawnia się przerażająca prawda. Wszyscy mamy niezliczone przeszłości zbiegające się w tej jednej teraźniejszości – a nasza przyszłość jest przerażająco skończona. We wszechświecie są umysły liczące miliardy lat, które nami sterują i mają wobec nas pewne plany, niezbyt przyjazne.
Czas walczyć, by odzyskać kontrolę nad swoim losem i uniknąć zagłady….""")
    books.add_book(connention, 63, "Hyperion", "Dan Simmons", "978-83-8064-030-6", """W obliczu zbliżającej się nieuchronnie międzygalaktycznej wojny na planetę Hyperion przybywa siedmioro pielgrzymów: Kapłan, Żołnierz, Uczony, Poeta, Kapitan, Detektyw i Konsul. Mają za zadanie dotrzeć do mitycznych grobowców, by znaleźć w nich budzącą grozę istotę. Zna ona być może metodę, która pozwoli zapobiec zagładzie całej ludzkości. Każdy z pielgrzymów może przedstawić jej swoją prośbę, lecz wysłuchany zostanie tylko jeden. Pozostali będą musieli zginąć.""")
    books.add_book(connention, 64, "Upadek Hyperiona", "Dan Simmons", "978-83-66065-70-3", """Tajemnicze Grobowce Czasu otwierają się. W rękach Dzierzby, który się z nich wynurzył, może spoczywać los całego rodzaju ludzkiego. Wygnańcy przypuścili szturm na Hegemonię Człowieka. Stworzone przez nas Sztuczne Inteligencje obróciły się przeciwko nam w próbie zbudowania Najwyższego Intelektu: Boga. Boga Maszyn. Jego powstanie może oznaczać unicestwienie ludzkości.
Za sprawą nieznanych sił losy Hegemonii, Wygnańców, SI i całego wszechświata splatają się wokół Dzierzby.
Oto wspaniała wizja przyszłości, w której wysoko rozwinięta technika miesza się z pradawnymi religiami, odkrycia naukowe łączą się z ponadczasową tajemnicą, a niezrównana ekstaza płynnie przechodzi w obezwładniającą zgrozę.""")
    books.add_book(connention, 65, "Solaris", "Stanisław Lem", "978-83-962222-0-6", """W Solaris Stanisław Lem podejmuje jeden z najpopularniejszych tematów literatury fantastycznej - temat Kontaktu. Z obcą cywilizacją, odmienną formą życia, a może po prostu z Nieznanym, tego Lem jednoznacznie nie dopowiada. Być może dlatego Solaris po kilkudziesięciu lat od pierwszego wydania wciąż fascynuje.""")
    books.add_book(connention, 66, "Star Trek. Rebelia", "J. M. Dillard", "", """Kapitan Jean-Luc Picard nie zdawał sobie sprawy, że nadejdzie dzień, w którym będzie musiał złamać rozkazy Federacji w imię „mniejszego dobra”. Jest gotów poświęcić życie swoje i załogi, chroniąc skrywany od pokoleń sekret Ba'ku, spokojnego i pokojowo nastawionego ludu. Okazuje się jednak, że niektórzy zapłacą każdą cenę, by posiąść tajemnicę wiecznej młodości. Załoga statku USS Enterprise staje przed poważnymi dylematami, a Picard musi zdecydować, czy powinien wypełnić swoje obowiązki, czy postąpić zgodnie z sumieniem i podszeptami serca. A czas ucieka...""")
    books.add_book(connention, 67, "Chór zapomnianych głosów", "Remigiusz Mróz", "978-83-7995-016-4", """Okręt badawczy „Accipiter” przemierza bezkres kosmicznej próżni, a jego załoga pogrążona jest w głębokiej kriostazie. Nieliczni świadomi są dramatu, który rozgrywa się na pokładzie.
Astrochemik Håkon Lindberg budzi się przedwcześnie z kriogenicznego snu i widzi, jak ginie jeden z ostatnich członków załogi. Prócz niego rzeź przetrwał tylko nawigator, Dija Udin Alhassan. Czy to on jest odpowiedzialny za fiasko misji? A może stoi za tym jakaś niewypowiedziana siła? Obca cywilizacja? Nieokreślony byt? Ludzkość podróżuje między gwiazdami, odkrywa miriady światów, ale nigdy nie napotkała żadnych oznak życia.
Chór zapomnianych głosów to SF z tempem właściwym powieściom sensacyjnym, intrygą iście kryminalną i klimatem rodem z horrorów. Zakończenie powinno zaskoczyć nawet najbardziej przewidującego czytelnika.""")
    books.add_book(connention, 68, "Echo z otchłani", "Remigiusz Mróz", "978-83-66517-64-6", """Kontynuacja Chóru zapomnianych głosów - bestsellerowej powieści z gatunku science-fiction Remigiusza Mroza. Dalsze losy Håkona Lindberga, Dija Udina Alhassana i Ellyse.
ISS Kennedy powrócił na Ziemię, która w niczym nie przypomina planety sprzed kilkuset lat. Po globalnym kataklizmie stała się jałowym pustkowiem, a na jej powierzchni przetrwali tylko nieliczni.
Ocalałe statki Ara Maxima są bezpieczne na orbicie, czekając na dalsze instrukcje tych, którzy podejmą się odbudowy ludzkości.
Co zdarzyło się na Ziemi? I czy okrętom naprawdę nic nie grozi? Wróg wygrał proelium i czeka gdzieś pośród gwiazd, świadomy istnienia gatunku ludzkiego.
Jeden z nich nadal znajduje się w kriokomorze Kennedy’ego. I będzie miał szansę, by odkupić swoje winy…""")

    # TODO: horror
    books.add_book(connention, 69, "Zły Czarnoksiężnik z OZ. Gra książkowa", "Jonathan Green", "", """Ciemne chmury zgromadziły się nad Krainą Oz. Jej los spoczywa w Twoich rękach. Czy będąc otoczonym ze wszystkich stron przez nieprzyjaciół, zdołasz odkryć sekrety Złego Czarnoksiężnika? Czy uda Ci się uratować pieska Toto z rąk Latających Małp i uniknąć zemsty Złej Czarownicy z Zachodu?
Przyszedł właśnie czas na Twoją wersję tej znanej historii!
Bohaterowie znani z klasycznej baśni Czarnoksiężnik z Krainy Oz powracają, aby stawić czoło nowemu zagrożeniu. Jednak na takiego przeciwnika nic nie mogło przygotować ani ich… ani Ciebie!
W Złym Czarnoksiężniku z Oz to TY decydujesz o losach bohaterów. Możesz wybrać jedną z 6 postaci, którą poprowadzisz przez karty opowieści. Ale uważaj! – od Ciebie zależy, czy ta misja zakończy się sukcesem.
Jesteś gotów, by wrócić do Krainy Oz?""")
    books.add_book(connention, 70, "Smętarz dla zwierzaków", "Stephen King", "978-83-8169-651-7", """Czasami martwe jest lepsze.
Zazwyczaj przeprowadzka to początek nowego życia, ale dla rodziny Creedów stała się początkiem ich końca. Mistrz horroru Stephen King zaprasza czytelników na wycieczkę do piekła i z powrotem!
Na świecie istnieją dobre i złe miejsca. Nowy dom rodziny Creedów w Ludlow był niewątpliwie dobrym miejscem - przytulną, przyjazną wiejską przystanią po zgiełku i chaosie Chicago. Cudowne otoczenie Nowej Anglii, łąki, las to idealna siedziba dla młodego lekarza, jego żony, dwójki dzieci i kota. Wspaniała praca, mili sąsiedzi i droga, po której nieustannie przetaczają się ciężarówki. Droga i miejsce za domem, w lesie, pełne wzniesionych dziecięcymi rękami nagrobków - to tam dzieci z miasteczka zakopują swe martwe zwierzaki. Ci, którzy nie znają przeszłości, zwykle ją powtarzają... i nie chcą słuchać ostrzeżeń.
Stephen King napisał tę powieść podczas pobytu w wynajętym domku w Orrington, w stanie Maine. Fakt ten niewiele by znaczył, gdyby nie cmentarz zwierząt, który znajdował się nieopodal…""")
    books.add_book(connention, 71, "Drakula", "Bram Stoker", "978-83-8091-074-4", """Dawno temu marzyłem o Drakuli. Znałem filmy z Bélą Lugosim i Christopherem Lee, zdobyte jakimś cudem na kasetach wideo, ale sama powieść pozostawała niedostępna. Cenzorzy w PRL niechętnie patrzyli na wampira, który boi się krzyża. Plotka głosi, że wydanie powieści Stokera zatrzymano wskutek protestu rumuńskiej ambasady.
Pamiętam swoją, dziecięcą jeszcze, radość, kiedy udało mi się zdobyć pierwsze polskie wydanie, na samym początku lat dziewięćdziesiątych. Niestety, nie było ono kompletne. Z treści wyleciały postacie i wątki. Nikt nie sprawdzał jakości przekładu. Drakula, jedna z najbardziej wpływowych książek, miała wyjątkowego pecha nad Wisłą.
Powieść, piekielnie nowoczesna w czasie jej powstania, do dziś inspiruje twórców kultury. Nasz świat byłby zupełnie inny, gdyby nie Drakula. A dla mnie ta edycja jest niewiarygodnym spełnieniem dziecięcego marzenia, to prezent podarowany samemu sobie sprzed lat, kiedy rozmyślałem o wampirach, wędrując po księgarniach.
Łukasz Orbitowski""")
    books.add_book(connention, 72, "Czarna Madonna", "Remigiusz Mróz", "978-83-66278-07-3", """Boeing 747 irlandzkich linii lotniczych miał wylądować w Tel Awiwie o trzeciej w nocy. Nigdy nie dotarł na miejsce, a kontakt z maszyną utracono gdzieś nad Morzem Śródziemnym. Na pokładzie znajdowało się 520 osób, w tym narzeczona Filipa, która miała odbyć pielgrzymkę do Bazyliki Grobu Świętego.
Przez pierwsze godziny Filip wierzy, że samolot się odnajdzie. Nic nie wskazuje na zamach, straż przybrzeżna nie odnajduje wraku, a co jakiś czas do kontroli lotów dociera sygnał z transpondera.
Co stało się z boeingiem? Jaki związek ma jego zniknięcie z podobnymi zdarzeniami?
I jakie znaczenie ma obraz Matki Bożej, nazywany Czarną Madonną?
Pierwsze odpowiedzi każą Filipowi sądzić, że niewiedza naprawdę jest błogosławieństwem.""")
    books.add_book(connention, 73, "Chudszy", "Richard Bachman", "", """Billy Halleck jest ucieleśnieniem Amerykańskiego Snu. Przykładny mąż, kochający ojciec, wzięty adwokat. Gdyby nie zagrażająca zdrowiu nadwaga, mógłby się uważać za człowieka bez problemów. Wygląda na to, że szczęście dopisuje mu nawet wtedy, gdy zostaje postawiony przed sądem za śmiertelne potrącenie Cyganki- wyrok jest uniewinniający. Okazuje się jednak, że kara go nie ominie. Wymierza ją oburzony werdyktem ojciec ofiary, stary Cygan, który patrząc na wychodzącego z gmachu sądu sprawcę wypadku, szepcze tylko jedno słowo: CHUDSZY. I wtedy się zaczyna...""")
    books.add_book(connention, 74, "Lśnienie", "Stephen King", "", """To jeden z najlepszych współczesnych horrorów. Nastrój grozy i napięcia potęguje się w niej z każdą minutą. Pięcioletni chłopiec Danny znalazł się z rodzicami w opustoszałym na zimie hotelu. Wrażliwe, obdarzone zdolnościami wizjonerskimi dziecko odbiera fluidy czające się w jego murach były one świadkami krwawych porachunków świata przestępczego i milionerów. Straszliwe zdarzenia, które kończą fabułę, są jednak niczym w porównaniu z przejściami psychicznymi bohaterów.""")
    books.add_book(connention, 75, "Cztery pory roku", "Stephen King", "978-83-8125-257-7", """WAŻNA JEST OPOWIEŚĆ, NIE OPOWIADAJĄCY…
4 minipowieści, z których 3 doczekały się ekranizacji. Najsłynniejsza z nich – Skazani na Shawshank z Timem Robbinsem i Morganem Freemanem – otrzymała aż 7 nominacji do Oscarów.
Skazani na Shawshank
Więzień odsiadujący karę dożywocia za podwójne – niepopełnione! - morderstwo obmyśla plan ucieczki. Tak misterny, że może zwieść nie tylko sadystycznych strażników, ale i towarzyszy niedoli.
Pojętny uczeń
Hitlerowski zbrodniarz ukrywający się pod przybranym nazwiskiem w amerykańskim miasteczku znajduje „godnego” siebie ucznia w osobie trzynastoletniego chłopca.
Ciało
Czterech nastolatków wyrusza w drogę, by po raz pierwszy w życiu zobaczyć zwłoki…
Metoda oddychania
Historia makabrycznego porodu, który pewien lekarz z talentem do snucia opowieści odebrał w wigilijny wieczór.""")
    books.add_book(connention, 76, "Ręka mistrza", "Stephen King", "", """Edgar Freemantle w ciężkim wypadku samochodowym traci rękę i zdrowe zmysły. Nękany niekontrolowanymi napadami szału, musi zacząć życie od początku. Za radą psychologa wyrusza na Duma Key, olśniewająco piękną i odludną wyspę na wybrzeżu Florydy, należącą do sędziwej Elizabeth Eastlake. Wynajmuje tam dom, wiedząc tylko jedno: chce rysować. Tworzone z chorobliwą pasją obrazy Edgara są owocem talentu, nad którym stopniowo przestaje mieć kontrolę. Kiedy tragiczne dzieje rodziny Eastlake’ów zaczynają wyłaniać się z mroków przeszłości, nieposkromiona moc dzieł Freemantle’a objawia swe coraz bardziej przerażające i niszczycielskie możliwości.""")
    books.add_book(connention, 77, "Doktor Sen", "Stephen King", "978-83-8169-849-8", """Kontynuacja bestsellerowego „Lśnienia”!
Pamiętacie małego chłopca obdarzonego niezwykłą mocą? Chłopca nękanego przez duchy? Chłopca uwięzionego w odludnym hotelu wraz z opętanym ojcem? Możecie już poznać jego dalsze losy!
Grupa staruszków nazywająca się Prawdziwym Węzłem przemierza autostrady Ameryki w poszukiwaniu pożywienia. Z pozoru są nieszkodliwi - emeryci odziani w poliester, nierozstający się ze swoimi samochodami turystycznymi. Jednak Dan Torrance już wie, a rezolutna dwunastolatka Abra Stone wkrótce się przekona, że Prawdziwy Węzeł to prawie nieśmiertelne istoty żywiące się substancją wytwarzaną przez poddane śmiertelnym torturom dzieci obdarzone tym samym darem, co Dan.
Nękany przez mieszkańców hotelu Panorama, w którym jako dziecko spędził jedną straszliwą zimę, Dan przez dziesięciolecia błąka się po Ameryce, usiłując zrzucić z siebie odziedziczone po ojcu brzemię beznadziei, alkoholizmu i przemocy. Ostatecznie odnajduje swoje miejsce w małym miasteczku w New Hampshire, we wspierającej go grupie Anonimowych Alkoholików i w domu opieki, gdzie zachowana z lat dzieciństwa resztka mocy pozwala mu nieść ulgę umierającym w ostatnich chwilach ich życia. Staje się znany jako "Doktor Sen".
Kiedy Dan poznaje efemeryczną Abrę Stone, jej nadzwyczajny dar budzi drzemiące w nim demony i każe mu stanąć do boju o jej duszę i przetrwanie. To epicka batalia między dobrem i złem, krwawa, pełna rozmachu opowieść, która zachwyci miliony miłośników "Lśnienia" i zadowoli każdego, kto dopiero teraz wkracza w świat tej już klasycznej pozycji w dorobku Kinga.""")
    books.add_book(connention, 78, "Podpalaczka", "Stephen King", "978-83-8125-760-2", """Charlie McGee jest dzieckiem wyjątkowym, obdarzonym nadludzkim darem, zdolnością pirokinezy: potrafi siłą woli zdalnie rozniecić ogień.
Rodzice dziewczynki, Vicky i Andy, uczestniczyli kiedyś jako ochotnicy w tajemniczym eksperymencie sponsorowanym przez tajną amerykańską agencję rządową, przybudówkę CIA zwaną Sklepikiem. Pozwalając sobie wstrzyknąć Próbę Sześć – rzekomo nieszkodliwą substancję halucynogenną, w rzeczywistości niebezpieczny środek chemiczny powodujący trwałe zmiany w przysadce mózgowej i chromosomach – zostali nieświadomie wyposażeni w niezwykłe talenty, obejmujące telekinezę, hipnozę i telepatię.
Daleko idące skutki eksperymentu kładą się cieniem na życiu poddanej nieustannej obserwacji rodziny McGee, zmieniając je w koszmar. Po zamordowaniu Vicky przez agentów Sklepiku, nie chcąc, by Charlie stała się kolejnym „królikiem doświadczalnym” CIA, Andy decyduje się na ucieczkę.
Pościg za dwójką zbiegów prowadzi John Rainbird, zabójca na usługach Sklepiku, dla którego zabicie dziecka staje się celem samym w sobie.
Czy Charlie użyje pirokinetycznej mocy, by ocalić siebie i ojca? Zdaniem naukowców, byłaby nawet w stanie samoczynnie doprowadzić do eksplozji atomowej...""")

    # TODO: poezja
    books.add_book(connention, 79, "Faust. Tragedii część pierwsza i druga", "Johann Wolfgang von Goethe", "", """Pełne wydanie „Fausta”, obu części tragedii w nowym przekładzie Andrzeja Lama, umożliwia poznanie tego arcydzieła w całym jego obrazowym i myślowym bogactwie.""")
    books.add_book(connention, 80, "Treny", "Jan Kochanowski", "978-83-956761-6-1", "Treny Jana Kochanowskiego - wyjątkowy w polskiej literaturze cykl utworów napisanych po śmierci zmarłej córki poety – Urszuli.")
    books.add_book(connention, 81, "Sonety krymskie", "Adam Mickiewicz", "978-83-934341-6-9", """Chwilowo brak""")
    books.add_book(connention, 82, "Kwiaty zła", "Charles Pierre Baudelaire", "", """Najbardziej znane dzieło Charles’a Baudelaire’a, wydane w 1857 r. Kwiaty Zła operujące odważną erotyką, brzydotą oraz obrazami pełnymi śmierci i zła, wywołały skandal i proces sądowy, w wyniku którego poeta i wydawca zostali ukarani grzywną za niemoralność, a sześć wierszy usunięto. W tym niezwykłym zbiorku powracające motywy i tematy: Dobra i Zła, Boga i szatana, grzechu pierworodnego, poezji, kobiety, wina, kotów... koncentrują się wokół dwóch centralnych zagadnień: miłości i śmierci. To one łączą ze sobą i wyznaczają kontekst odczytań wszystkiego, co zajmuje uwagę poety, którego choroba splotła nierozerwalnie miłość i śmierć. Czym są Kwiaty zła? Jak powiedział Marcel Ruff, , parafrazując słowa Theofila Gautiera o „doskonałym poemacie”, są one wyrazem „natury wygnanej w niedoskonałość, a która chciałaby natychmiast, już na tej ziemi nawet, osiągnąć objawiony sobie raj”.""")
    books.add_book(connention, 83, "Świteź", "Adam Mickiewicz", "", """ Ktokolwiek będzisz w nowogródzkiej stronie,
Do Płużyn ciemnego boru
Wjechawszy, pomnij zatrzymać twe konie,
Byś się przypatrzył jezioru.
Świteź tam jasne rozprzestrzenia łona,
W wielkiego ksztalcie obwodu,
Gęstą po bokach puszczą oczerniona,
A gładka jak szyba lodu...""")
    books.add_book(connention, 84, "Pan Cogito", "Zbigniew Herbert", "978-83-65614-00-1", """Do lektur Pana Cogito należą proroctwa Izajasza i pisma filozofów, ale również codzienna gazeta. Znajduje się on w kręgu oddziaływania tysięcy lat europejskiej kultury, ale jest też pod naciskiem najnowszych mód i snobizmów o motylim żywocie. Nie jest o wiele mądrzejszy czy bardziej pewny swoich racji od rzeszy swych współczesnych i współziomków. Wyróżnia go to, że próbuje myśleć, że borykając się z niepewnością i zwątpieniem stara się mimo wszystko ocalić w sobie zdolność do niezależnego myślenia. I stąd jego imię. Herbert w pewnym sensie odwraca słowa& Kartezjusza; nie tylko „myślę, więc jestem”, ale również: skoro chcę istnieć naprawdę – muszę myśleć.
Stanisław Barańczak, „Polityka”, 1974""")
    books.add_book(connention, 85, "Chwila", "Wisława Szymborska", "", """Każdy z utworów zgromadzonych w tomie "Chwila" to krystalicznie czysty, precyzyjny i zwarty minitraktat: filozoficzny, metafizyczny, egzystencjalny. Szymborska mówi o sprawach najważniejszych w sposób skłaniający do odkrywczych medytacji i przemyśleń.""")
    books.add_book(connention, 86, "Słoń Trąbalski", "Julian Tuwim", "978-83-287-0102-1", """Chwilowo brak.""")
    books.add_book(connention, 87, "Monachomachia", "Ignacy Krasicki", "", """Po raz pierwszy wydany anonimowo w 1778 r. poemat, opowiadający o walce między dominikanami, a karmelitanami. Satyra, przyprawiona groteską i wszechobecnym komizmem. Po raz pierwszy wydana, wywołała oburzenie ogółu, spowodowane otwartym, nieskrywanym wystąpieniem Krasickiego przeciw zakonnikom.""")
    books.add_book(connention, 88, "Słońce i jej kwiaty", "Rupi Kaur", "978-83-7515-485-6", """„Słońce i jej kwiaty” to tętniące kobiecością utwory o dojrzewaniu i samoświadomości. Rupi Kaur ponownie – lecz z jeszcze większą mocą – w krótkich poetyckich formach wyraża troski, pragnienia i radości wielu kobiet. Daje im siłę, by czerpały ze swoich korzeni i doświadczeń pełnymi garściami. Przekonuje, że podobnie jak kwiaty ludzie też muszą czasem zwiędnąć, by rozkwitnąć na nowo.""")

    # TODO: reportaż
    books.add_book(connention, 89, "Zdążyć przed Panem Bogiem", "Hanna Krall", "", """Kanoniczna książka, najsłynniejsza, obowiązkowa.
Literacki dokument o wyścigu ze śmiercią.
Od ponad czterdziestu lat Zdążyć przed Panem Bogiem pozostaje klasykiem polskiego reportażu i jedną z najbardziej przejmujących opowieści o powstaniu w getcie warszawskim w kwietniu 1943 roku i losach polskich Żydów, jakie stworzyła literatura XX wieku.
To książka, która powstała z rozmów z Markiem Edelmanem, lekarzem, podczas wojny jednym z przywódców powstania.
Marek Edelman opowiada o wojnie i o medycynie. O tym, czym jest godna śmierć i godne życie. Jest to także opowieść o ludziach, którzy mu towarzyszyli – o powstańcach, zakonnicach, dawnych akowcach, kobietach, które kochał, o pacjentach i o lekarzach.
„ - Pan Bóg już chce zgasić świeczkę, a ja muszę szybko osłonić płomień, wykorzystując Jego chwilową nieuwagę. Niech się pali choć trochę dłużej, niż On by sobie życzył. To jest ważne: On nie jest za bardzo sprawiedliwy. To jest również przyjemne, bo jeżeli się coś uda – to bądź co bądź Jego wywiodło się w pole…
– Wyścig z Panem Bogiem? Cóż to za pycha!
– Wiesz, kiedy człowiek odprowadza innych ludzi do wagonów, to może mieć z Nim później parę spraw do załatwienia. A wszyscy przechodzili koło mnie, bo stałem przy bramie od pierwszego do ostatniego dnia. Wszyscy, czterysta tysięcy ludzi przeszło koło mnie”. (fragment książki)""")
    books.add_book(connention, 90, "Kwiat pustyni. Z namiotu Nomadów do Nowego Jorku", "Waris Dirie, Cathleen Miller", "", """Waris urodziła się w Somalii, w plemieniu pustynnych wędrowców, wychowała się pośród kóz, bydła i wielbłądów.
W wieku 13 lat dziewczęta z tego plemienia są poddawane rytuałowi obrzezania i wydawane za mąż. Jednak bohaterka książki została poddana obrzezaniu w wieku około 5 lat, a miała być wydana za mąż dopiero w wieku 13 lat
Te dwa wydarzenia zaważyły na całym przyszłym życiu Waris.""")
    books.add_book(connention, 91, "Polska odwraca oczy", "Justyna Kopińska", "978-83-8139-496-3", """Nowa książka najczęściej nagradzanej dziennikarki 2015 roku.
W zbiorze znajduje się reportaż o dręczonych nieletnich pacjentach szpitala psychiatrycznego w Starogardzie Gdańskim („Oddział chorych ze strachu”), tuszowaniu przez policję najtrudniejszych spraw związanych z zabójstwami („Ten trup się nie liczy”) oraz – nigdy niepublikowana – rozmowa z żoną Mariusza Trynkiewicza osadzonego w ośrodku specjalnym w Gostyninie, zabójcy czterech chłopców.
Z reportaży Kopińskiej wyłania się obraz nieskutecznego wymiaru sprawiedliwości i ludzi pozostawionych z poczuciem krzywdy. Po publikacji jej tekstów przestępcy trafiali do więzienia, a w prawie wprowadzano zmiany dotyczące bezpieczeństwa w instytucjach zamkniętych dla dzieci.""")
    books.add_book(connention, 92, "Cesarz", "Ryszard Kapuściński", "978-83-07-03442-3", """Jeden z największych bestsellerów światowych. Przedmiotem reportażu-powieści są ludzie dworu cesarza Etiopii Hajle Sellasje zmarłego w 1975 roku. Ukazując ich służalczość, lizusostwo, strach, pazerność, uległość oraz walkę o względy władcy, Kapusciński w mistrzowski sposób przedstawia ponure kulisy jego panowania. Książka ma uniwersalny charakter, obnaża mechanizmy władzy nie tylko politycznej. Cesarzem Ryszard Kapuściński rozpoczął karierę międzynarodowa i nadał reportażowi wymiar literacki.""")
    books.add_book(connention, 93, "Heban", "Ryszard Kapuściński", "978-83-07-03445-4", """Heban to złożona z wielu wątków fascynująca, nowoczesna powieść-relacja z „ekspedycji” w głąb Czarnego Kontynentu, ukazująca Afrykę u progu XXI wieku, Afrykę rozdzieraną wojnami, głodem, epidemiami i korupcją.
[...]„Heban” Ryszarda Kapuścińskiego to dramatycznie stawiane pytanie do nas, Europejczyków: czy z takim zapomnianym, umierającym kontynentem będziemy mogli spokojnie żyć?""")
    books.add_book(connention, 94, "Rozmowy z katem", "Kazimierz Moczarski", "978-83-240-4214-2", """Polski bohater więziony miesiącami przez własnych rodaków. Dzień i noc w towarzystwie mordercy, kata warszawskiego getta, generała SS Jürgena Stroopa.
„Do widzenia, Herr Moczarski, do zobaczenia niedługo u św. Piotra!” – mówi Stroop na pożegnanie, idąc na egzekucję. Czy można sobie wyobrazić podobną sytuację? Taki sam wyrok, wyrok śmierci, wydany na bezlitosnego nazistę i bohatera Armii Krajowej przez Polskę Ludową?
Chociaż oprawcy w więzieniu mokotowskim mają wyjątkową wyobraźnię – poddają Moczarskiego 49 rodzajom tortur – on sam również wpada na oryginalny pomysł. Zachęca nazistę do szczerych zwierzeń. Zapamiętuje wszystko.
Dziś możemy czytać jedną z najważniejszych rozmów, jakie kiedykolwiek się odbyły. To rozmowa śmiertelnych wrogów w celi śmierci. Różnica między nimi jest taka, że tylko jeden z nich dostał sprawiedliwy wyrok.""")
    books.add_book(connention, 95, "Dywizjon 303", "Arkady Fiedler", "978-83-7823-984-0", """Dywizjon 303" jest pięknym i porywającym reportażem z pola bitwy. Autor skupia się przede wszystkim na najważniejszych wydarzeniach z udziałem Polaków. Nie brakuje również "zbliżeń" na konkretne osoby. Mamy okazję poznać wyczyny takich asów, jak Witold Urbanowicz czy sierżant Frantiszek. Warto zwrócić uwagę na to, że wszystkie powietrzne zmagania obudowane są wątkami cywilnymi.
Dywizjon 303" powstał "na rozkaz" Naczelnego Wodza Polskich Sił Zbrojnych generała Władysława Sikorskiego, a jego pierwsze wydanie miało miejsce jeszcze w 1942 roku. Sam autor tak oto wypowiada się na temat genezy swojego dzieła: "Spośród wszystkich moich książek Dywizjon 303 jest chyba utworem pisanym najbardziej na gorąco, pod bezpośrednim wrażeniem rozgrywających się w 1940 roku wypadków: pierwsze stronice powstawały już podczas ostatniej fazy owego osobliwego dramatu, nazwanego Bitwą o Brytanię, a ostatnie stronice kończyłem kilkanaście tygodni później, kiedy wciąż jeszcze, niby echo owej bitwy, warczały nocą nad Londynem motory Luftwaffe i padały bomby na miasto.""")
    books.add_book(connention, 96, "Z nienawiści do kobiet", "Justyna Kopińska", "978-83-8139-494-9", """Książka najczęściej nagradzanej dziennikarki.
Zbiór reportaży „Z nienawiści do kobiet” to historie o najważniejszych sprawach, którymi żyła cała Polska.
Książkę otwiera premierowa opowieść syna o Violetcie Villas, artystce, która odniosła ogromny sukces, była podziwiana przez miliony, a zmarła w samotności. Tekst „Ksiądz pedofil odprawia dalej” to szokująca historia trzynastoletniej dziewczynki podstępem wywiezionej od rodziców i gwałconej przez księdza, a reportaż „Z nienawiści do kobiet” pokazuje, jak wojsko zamiata pod dywan molestowanie seksualne kobiet przez wysokiej rangi oficera.
Z twórczości Justyny Kopińskiej wyłania się obraz nieskutecznego wymiaru sprawiedliwości i ludzi pozostawionych z poczuciem krzywdy. Po publikacji jej tekstów przestępcy trafiali do więzień, a w prawie wprowadzano zmiany dotyczące bezpieczeństwa w instytucjach zamkniętych.""")
    books.add_book(connention, 97, "Czarnobylska modlitwa. Kronika przyszłości", "Swietłana Aleksijewicz", "978-83-8049-279-0", """UWAGA!!! Książka została wcześniej wydana pt.:"Krzyk Czarnobyla".
"26 kwietnia 1986 o godzinie pierwszej minut dwadzieścia trzy i pięćdziesiąt osiem sekund seria wybuchów obróciła w ruinę reaktor i czwarty blok energetyczny elektrowni atomowej w położonym niedaleko granicy białoruskiej Czarnobylu. Katastrofa czarnobylska była najpotężniejszą z katastrof technologicznych XX wieku."
Dwadzieścia lat później Swietłana Aleksijewicz wróciła do Czarnobyla. Rozmawiała z ludźmi, dla których ten dzień był końcem świata, którzy żyć nie powinni, ale przeżyli i żyją, bo żyć trzeba. A oni opowiedzieli jej o tym, co wydarzyło się wtedy, i o tym, co jest tam dziś. O ponad dwóch milionach Białorusinów, których zapomniano przesiedlić poza strefę skażoną, o dzieciach bez włosów, o zwierzętach o smutnych oczach, które zamieszkały w porzuconych domach, o dziwnych stworach, które pojawiły się w rzekach i lasach. I o tym, że mimo wszystko ludzie chcą być szczęśliwi.
Podobnie jak w książce o radzieckich żołnierkach wybitna białoruska dziennikarka stawia nas wobec bezlitosnej prawdy. To książka o apokalipsie, która nastąpiła pewnej kwietniowej nocy tuż za naszą wschodnią granicą.""")
    books.add_book(connention, 98, "Imperium", "Ryszard Kapuściński", "978-83-07-03487-4", """Bestseller 1993 roku, tłumaczony na całym świecie. Imperium to bodaj najwybitniejsze dokonanie indywidualnego, pełnego inwencji stylu reportażu Kapuścińskiego, będącego niedościgłym wzorem dla największych dziennikarzy dzisiejszych czasów; ukazuje uchwycony na gorąco, w pełnych wielorakich znaczeń przybliżeniach, proces rozpadu Związku Radzieckiego – ostatniego imperium kończącego się stulecia.""")

    # TODO: literatura piękna
    books.add_book(connention, 99, "1984", "George Orwell", "", """Okrutna i sugestywna wizja świata, w którym rządzi przemoc i strach, a władza panuje nie tylko nad losem człowieka, ale też nad jego myślami i uczuciami. Boleśnie aktualna opowieść o pragnieniu władzy i konsekwencjach jej nadużywania.
Zarazem to przejmująca, głęboko ludzka opowieść o samotności, o tęsknocie do miłości, wolności, prawdy. Historia tragicznej pary kochanków, Winstona i Julii, czytana na całym świecie, często w podziemnych lub przemycanych wydaniach, była głosem ostrzeżenia przed zniewoleniem umysłu. Użyte w niej pojęcia – „nowomowa”, „Policja Myśli”, „dwójmyślenie” czy „Wielki Brat” – weszły do języka potocznego wielu narodów.
Literackie mistrzostwo świata! Pozycja obowiązkowa!""")
    books.add_book(connention, 100, "Wyspa", "Eustachy Rylski", "", """Eustachy Rylski jest nazywany alchemikiem słowa oraz mistrzem języka i wirtuozem ukrytych sensów. Sam wyznaje skromnie: „Mam stuprocentową pewność, że swoją twórczością nie rozsupłam tajemnicy istnienia. Od czasu do czasu jednak próbuję”. Każda z opowiedzianych przez niego historii przybliża nas do tej tajemnicy bardziej i choć na chwilę zatrzymuje w zachwycie.
Zbiór Wyspa to cztery opowieści połączone jednym motywem w tle – morzem. Bohaterowie – dziewczyna z prowincji szukająca szczęścia, niepokorny ksiądz-playboy, sędziwy pisarz czy enigmatyczny wczasowicz – postawieni w niecodziennych, często ekstremalnych sytuacjach, muszą stawić czoła rzeczywistości i własnym charakterom. Snując opowieść o konkretnych ludziach, autor przygląda się naszym oczekiwaniom wobec świata i próbuje uchwycić rozdźwięk między tym, co myślimy i czujemy, a tym, co ostatecznie czynimy i mówimy.""")
    books.add_book(connention, 101, "Bowie w Warszawie", "Dorota Masłowska", "", """Nowa książka Doroty Masłowskiej. Opowieść o wielkim, a przede wszystkim małym świecie i rozpaczliwym poszukiwaniu w nim wolności.
Trwa gierkowska dekada lat 70. David Bowie, podróżując z Moskwy do Berlina, zatrzymuje się na krótką chwilę w Warszawie. Jego na pozór niewiele znaczący pobyt w polskiej stolicy obrósł legendą jako ucieleśnienie tego, co niedoścignione i niedostępne, smuga koloru i blasku w powszechnej szarzyźnie.
Tymczasem w jednym z dusznych i ciasnych warszawskich mieszkań nie może spać plutonowy Wojciech Krętek. Wrażliwy i emocjonalny milicjant próbuje rozwikłać sprawę niejakiego Dusidamka z Mokotowa.
Siejący postrach oprawca zdaje się jednak tylko symbolem pomniejszych przemocy i opresji, których mieszkanki Warszawy doświadczają na każdym kroku od świata i siebie nawzajem.
Co łączy króla muzyki z seryjnym dusicielem? Dowiecie się w opowieści o marzeniach i niespełnieniach.""")
    books.add_book(connention, 102, "Lata", "Annie Ernaux", "", """Annie Ernaux to bez wątpienia jedna z najważniejszych współczesnych pisarek francuskich, a jej autobiograficzne Lata po raz pierwszy ukazują się po polsku.
„Czy byłabym szczęśliwsza, mając inne życie?” – zdaje się stale pytać Ernaux, prowadząc nas przez kolejne dekady swej biografii, które w mistrzowskim laboratorium jej prozy stają się zarazem biografią całego pokolenia. Od czasów niedostatku po lata kapitalistycznego przesytu. Od powojennej młodości, kiedy rytm życia w małym normandzkim miasteczku wyznaczały święta religijne, po dorosłość, kiedy z religijną gorliwością czytało się Simone de Beauvoir. Od wstydu wychowania w robotniczej rodzinie po wstydliwe przyjemności klasy średniej. A wszystko to na tle wielkiej historii, której motywem przewodnim było wyzwolenie. Wyzwolenie polityczne, wyzwolenie seksualne, wyzwolenie z klasowych ograniczeń. Ernaux mierzy się z zagadnieniami rewolucji obyczajowej, postępującego konsumpcjonizmu i sekularyzacji, przywołuje przełomowe momenty dla historii Francji i Europy. „Chciałabym te liczne obrazy siebie, rozdzielone, niezsynchronizowane, połączyć nicią opowieści o swojej egzystencji od narodzin w czasie II wojny światowej aż do dzisiaj. O istnieniu poszczególnym, lecz jednocześnie wtopionym w historię pokolenia”.
Choć Ernaux boleśnie odsłania własne korzenie, udaje się jej zachować dystans, a dzięki brawurowej formie literackiej i wielkiej pisarskiej odwadze oddaje czytelnikom dzieło wybitne i kompletne – opowieść o sobie, konkretnej kobiecie, i o całej generacji, o każdym z nas.""")
    books.add_book(connention, 103, "Komodo", "David Vann", "978-83-961899-6-7", """Na zaproszenie starszego brata Roya, Tracy wyjeżdża z Kalifornii i wraz z matką dołącza do niego w Indonezji, na jednej z wysp Parku Narodowego Komodo. Dla bohaterki, ignorowanej przez męża i zmęczonej wychowywaniem pięcioletnich bliźniaków, ta egzotyczna wycieczka ma być długo wyczekiwanym urlopem w raju: nurkowanie, oglądanie podwodnego świata mant i rekinów, relaks. To również okazja do odnowienia kontaktu z Royem prowadzącym chaotyczne życie po rozwodzie i oddalającym się od krewnych.
Jednak niedługo po przyjeździe na wyspę napięcie między członkami rodziny zaczyna narastać – wracają zadawnione pretensje i urazy z dzieciństwa. Tracy powoli traci grunt pod nogami przytłoczona falą wspomnień, żalu i goryczy. Rozpoczyna się walka i z każdym kolejnym zanurzeniem w głębinie przybiera na sile, aż w końcu sięga punktu, z którego nie ma już odwrotu.
W kolejnej publikowanej w Polsce książce David Vann, autor Legendy o samobójstwie, Halibuta na Księżycu i Brudu, potwierdza ogromny talent do zaglądania w głąb ludzkiego umysłu, budując przejmujący portret głównej bohaterki. Przenikliwa i zaskakująco trafna analiza kobiecej duszy, targających nią emocji, skutków zmagania się z codziennymi trudnościami i relacji mąż–żona oraz dziecko–matka sprawiają, że czytelnik niepostrzeżenie zatapia się w tej powieści.
Vann maluje portret kobiety bez czułości i taryfy ulgowej. Empatyczna, lecz mrożąca krew w żyłach.
„ELLE” (Francja)
Zanurzenie się w nowej powieści Davida Vanna jest nie tylko metaforyczne: wspólnie z bohaterami wkładamy strój nurka, sprawdzamy butlę z tlenem i wraz z najbliższą rodziną, która żywi do nas dawno skrywane urazy, schodzimy dwadzieścia metrów pod wodę… a tam okazuje się, że rekiny to nie zawsze najbardziej niebezpieczne stworzenia, które napotykamy w życiu.
„Livres Hebdo”""")
    books.add_book(connention, 104, "Gujcio", "Steven Rowley", "978-83-8234-411-0", """Rozpalająca serce opowieść o trudnych chwilach, w których rodzina okazuje się lekiem na największe smutki.
Patrick, dawna gwiazda telenoweli i wyoutowany gej, żyje spokojnym życiem samotnika. Gdy jego brat, po śmierci żony, w desperacji powierza mu swoje dzieci, cały świat staje do góry nogami. Chociaż Patrick zgadza się przyjąć bratanków pod swój dach, to najchętniej widziałby ich u siebie tylko w święta i weekendy.
Opieka nad dziećmi to zawsze wyzwanie dla kogoś, kto idei posiadania potomstwa nie chciał nigdy nawet dotknąć kijem. Rodzeństwo szybko rozprawia się z wygodnym życiem Patricka. Z czasem jednak podopieczni stają się dla mężczyzny jasnym punktem, który pozwala mu zmienić dotychczasowe wyobrażenie o świecie i o samym sobie. Czy mimo wielu przeszkód uda im się zbudować więź w trudnym dla nich wszystkich czasie?
"Gujcio" to najświeższa pozycja w dorobku słynącego ze wzruszających opowieści Stevena Rowleya. Pierwszy raz przetłumaczony na polski, pisarz zachwyci wszystkich szukających słodko-gorzkich historii, które przywracają wiarę w szczęście.""")
    books.add_book(connention, 105, "Ekstra rok z życia introwertyczki", "Jessica Pan", "978-83-8234-413-4", """Humorystyczna opowieść o wewnętrznym przewrocie.
Co by się stało, gdyby nieśmiała introwertyczka żyła przez rok niczym najprawdziwsza towarzyska ekstrawertyczka? Co by było, gdyby świadomie i dobrowolnie stawiała się w niebezpiecznych sytuacjach społecznych, których normalnie unikałaby za wszelką cenę? Jessica Pan postanawia to sprawdzić.
Kiedy Jess znalazła się bez pracy i przyjaciół, nie mogła powstrzymać się od rozważań, jak mogłoby wyglądać jej życie, gdyby była choć trochę bardziej… otwarta. Gdyby podążała za potrzebą nowych doświadczeń. Gdyby poznawała wciąż nowych ludzi. Gdyby bardziej od chęci powrotu do domu przywiązana była do stołka przy barze. Złożyła więc sobie przysięgę: przez rok postara się żyć tak, jak nigdy nie chciała. Improwizacje, samotne wakacje, rozmowy z nieznajomymi w metrze - to tylko kilka z punktów realizowanych podczas jej podróży w głąb siebie… której natychmiast pożałowała.
"Ekstra rok z życia introwertyczki" to prawdziwy meldunek z frontu. Czy życie ekstrawertyka jest rzeczywiście łatwiejsze? A może to koszmar, za jaki uważają je wszyscy introwertycy? Kto jak kto, ale Jess Pan na pewno się tego dowie.""")
    books.add_book(connention, 106, "To Paradise", "Hanya Yanagihara", "", """Chwilowo brak.""")
    books.add_book(connention, 107, "Grubaska", "Patrycja Żurek", "", """Kiedy jedzenie staje się sensem Twojego życia…
Dolores nie ma łatwego życia, nie tylko ze względu na imię, ale również na tuszę. Jest wyśmiewana, a żyjąc pod pantoflem matki nie potrafi się wyrwać i rozpocząć samodzielnego życia. Wszystko jednak zmienia się, kiedy zachodzi w ciąże i spotyka mężczyznę, który może być jej szansą wyrwanie się z toksycznego środowiska.
Jedna dziewczyna funkcjonująca w trzech pokoleniach, tak od siebie różne, tak inaczej nastawionych do jedzenia.
Grubaska to wyjątkowa historia o kompulsywnym jedzeniu, relacjach międzypokoleniowych i uzależnieniu od najbliższych sobie osób.""")
    books.add_book(connention, 108, "Trucicielka", "Éric-Emmanuel Schmitt", "", """Marie wyznaje na spowiedzi, że zamordowała swoich trzech mężów. Czy opisane przez nią zbrodnie to prawda, czy tylko perfidna gra, w której stawką jest dusza młodego księdza?
Obsesja towarzyszy wszystkim bohaterom opowiedzianych w Trucicielce historii. Każe im walczyć – o rodzinę, sławę, miłość. Niszczy, ale czasem daje drugą szansę. Schmitt krok po kroku odsłania mechanizm obsesji – pokazuje, jak łatwo jedna myśl może zatruć życie. Opisując zmagania swoich bohaterów, autor uczy nas jednak czegoś ważnego: że nigdy nie jest za późno na zmianę, nawet jeśli nie zawsze dane nam będzie szczęśliwe zakończenie.
Trucicielka to jedna z najpopularniejszych książek Érica-Emmanuela Schmitta, znakomitego francuskiego pisarza i filozofa. W 2010 roku autor otrzymał za nią prestiżową Le Prix Goncourt de la Nouvelle.""")

    # books.delete_book(connention, "Zemsta")
    book = books.get_all_books(connention)
    for b in book:
        print(b)
